# -*- coding: utf-8 -*-
"""
   The language ids and language names choices obtained for the pycountry.
"""

from metashare.repository.supermodel import _make_choices_from_list
LANGUAGEID_CHOICES = _make_choices_from_list([
u"aa", u"ab", u"ace", u"ach", u"ada", u"ady", u"afa", u"afh", u"af", u"ain",
u"ak", u"akk", u"sq", u"ale", u"alg", u"alt", u"am", u"ang", u"anp", u"apa",
u"ar", u"arc", u"an", u"hy", u"arn", u"arp", u"art", u"arw", u"as", u"ast",
u"ath", u"aus", u"av", u"ae", u"awa", u"ay", u"az", u"bad", u"bai", u"ba",
u"bal", u"bm", u"ban", u"eu", u"bas", u"bat", u"bej", u"be", u"bem", u"bn",
u"ber", u"bho", u"bh", u"bik", u"bin", u"bi", u"bla", u"bnt", u"bs", u"bra",
u"br", u"btk", u"bua", u"bug", u"bg", u"my", u"byn", u"cad", u"cai", u"car",
u"ca", u"cau", u"ceb", u"cel", u"ch", u"chb", u"ce", u"chg", u"zh", u"chk",
u"chm", u"chn", u"cho", u"chp", u"chr", u"cu", u"cv", u"chy", u"cmc", u"cop",
u"kw", u"co", u"cpe", u"cpf", u"cpp", u"cr", u"crh", u"crp", u"csb", u"cus",
u"cs", u"dak", u"da", u"dar", u"day", u"del", u"den", u"dgr", u"din", u"dv",
u"doi", u"dra", u"dsb", u"dua", u"dum", u"nl", u"dyu", u"dz", u"efi", u"egy",
u"eka", u"elx", u"en", u"enm", u"eo", u"et", u"ee", u"ewo", u"fan", u"fo",
u"fat", u"fj", u"fil", u"fi", u"fiu", u"fon", u"fr", u"frm", u"fro", u"frr",
u"frs", u"fy", u"ff", u"fur", u"gaa", u"gay", u"gba", u"gem", u"ka", u"de",
u"gez", u"gil", u"gd", u"ga", u"gl", u"gv", u"gmh", u"goh", u"gon", u"gor",
u"got", u"grb", u"grc", u"el", u"gn", u"gsw", u"gu", u"gwi", u"hai", u"ht",
u"ha", u"haw", u"he", u"hz", u"hil", u"him", u"hi", u"hit", u"hmn", u"ho",
u"hr", u"hsb", u"hu", u"hup", u"iba", u"ig", u"is", u"io", u"ii", u"ijo",
u"iu", u"ie", u"ilo", u"ia", u"inc", u"id", u"ine", u"inh", u"ik", u"ira",
u"iro", u"it", u"jv", u"jbo", u"ja", u"jpr", u"jrb", u"kaa", u"kab", u"kac",
u"kl", u"kam", u"kn", u"kar", u"ks", u"kr", u"kaw", u"kk", u"kbd", u"kha",
u"khi", u"km", u"kho", u"ki", u"rw", u"ky", u"kmb", u"kok", u"kv", u"kg",
u"ko", u"kos", u"kpe", u"krc", u"krl", u"kro", u"kru", u"kj", u"kum", u"ku",
u"kut", u"lad", u"lah", u"lam", u"lo", u"la", u"lv", u"lez", u"li", u"ln",
u"lt", u"lol", u"loz", u"lb", u"lua", u"lu", u"lg", u"lui", u"lun", u"luo",
u"lus", u"mk", u"mad", u"mag", u"mh", u"mai", u"mak", u"ml", u"man", u"mi",
u"map", u"mr", u"mas", u"ms", u"mdf", u"mdr", u"men", u"mga", u"mic", u"min",
u"mis", u"mkh", u"mg", u"mt", u"mnc", u"mni", u"mno", u"moh", u"mo", u"mn",
u"mos", u"mul", u"mun", u"mus", u"mwl", u"mwr", u"myn", u"myv", u"nah", u"nai",
u"nap", u"na", u"nv", u"nr", u"nd", u"ng", u"nds", u"ne", u"new", u"nia",
u"nic", u"niu", u"nn", u"nb", u"nog", u"non", u"no", u"nqo", u"nso", u"nub",
u"nwc", u"ny", u"nym", u"nyn", u"nyo", u"nzi", u"oc", u"oj", u"or", u"om",
u"osa", u"os", u"ota", u"oto", u"paa", u"pag", u"pal", u"pam", u"pa", u"pap",
u"pau", u"peo", u"fa", u"phi", u"phn", u"pi", u"pl", u"pon", u"pt", u"pra",
u"pro", u"ps", u"qu", u"raj", u"rap", u"rar", u"roa", u"rm", u"rom", u"ro",
u"rn", u"rup", u"ru", u"sad", u"sg", u"sah", u"sai", u"sal", u"sam", u"sa",
u"sas", u"sat", u"scn", u"sco", u"sel", u"sem", u"sga", u"sgn", u"shn", u"sid",
u"si", u"sio", u"sit", u"sla", u"sk", u"sl", u"sma", u"se", u"smi", u"smj",
u"smn", u"sm", u"sms", u"sn", u"sd", u"snk", u"sog", u"so", u"son", u"st",
u"es", u"sc", u"srn", u"sr", u"srr", u"ssa", u"ss", u"suk", u"su", u"sus",
u"sux", u"sw", u"sv", u"syc", u"syr", u"ty", u"tai", u"ta", u"tt", u"te",
u"tem", u"ter", u"tet", u"tg", u"tl", u"th", u"bo", u"tig", u"ti", u"tiv",
u"tkl", u"tlh", u"tli", u"tmh", u"tog", u"to", u"tpi", u"tsi", u"tn", u"ts",
u"tk", u"tum", u"tup", u"tr", u"tut", u"tvl", u"tw", u"tyv", u"udm", u"uga",
u"ug", u"uk", u"umb", u"und", u"ur", u"uz", u"vai", u"ve", u"vi", u"vo",
u"vot", u"wak", u"wal", u"war", u"was", u"cy", u"wen", u"wa", u"wo", u"xal",
u"xh", u"yao", u"yap", u"yi", u"yo", u"ypk", u"zap", u"zbl", u"zen", u"zgh",
u"za", u"znd", u"zu", u"zun", u"zza"])


LANGUAGENAME_CHOICES = _make_choices_from_list([
#EU
u"Bulgarian", u"Czech", u"Croatian", u"Danish",
u"Dutch; Flemish", u"English", u"Estonian",
u"Finnish", u"French", u"German",
u"Greek, Modern (1453-)",u"Hungarian",
u"Irish", u"Italian", u"Latvian",
u"Lithuanian", u"Maltese", u"Polish",
u"Portuguese", u"Romanian", u"Slovak",
u"Slovenian", u"Spanish; Castilian", u"Swedish",
#more
u"Afar", u"Abkhazian", u"Achinese", u"Acoli",
u"Adangme", u"Adyghe; Adygei", u"Afro-Asiatic languages", u"Afrihili",
u"Afrikaans", u"Ainu", u"Akan", u"Akkadian",
u"Albanian", u"Aleut", u"Algonquian languages", u"Southern Altai",
u"Amharic", u"English, Old (ca. 450-1100)", u"Angika", u"Apache languages",
u"Arabic", u"Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)", u"Aragonese", u"Armenian",
u"Mapudungun; Mapuche", u"Arapaho", u"Artificial languages", u"Arawak",
u"Assamese", u"Asturian; Bable; Leonese; Asturleonese", u"Athapascan languages", u"Australian languages",
u"Avaric", u"Avestan", u"Awadhi", u"Aymara",
u"Azerbaijani", u"Banda languages", u"Bamileke languages", u"Bashkir",
u"Baluchi", u"Bambara", u"Balinese", u"Basque",
u"Basa", u"Baltic languages", u"Beja; Bedawiyet", u"Belarusian",
u"Bemba", u"Bengali", u"Berber languages", u"Bhojpuri",
u"Bihari languages", u"Bikol", u"Bini; Edo", u"Bislama",
u"Siksika", u"Bantu languages", u"Bosnian", u"Braj",
u"Breton", u"Batak languages", u"Buriat", u"Buginese",
u"Burmese", u"Blin; Bilin", u"Caddo",
u"Central American Indian languages", u"Galibi Carib", u"Catalan; Valencian", u"Caucasian languages",
u"Cebuano", u"Celtic languages", u"Chamorro", u"Chibcha",
u"Chechen", u"Chagatai", u"Chinese", u"Chuukese",
u"Mari", u"Chinook jargon", u"Choctaw", u"Chipewyan; Dene Suline",
u"Cherokee", u"Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", u"Chuvash", u"Cheyenne",
u"Chamic languages", u"Coptic", u"Cornish", u"Corsican",
u"Creoles and pidgins, English based", u"Creoles and pidgins, French-based", u"Creoles and pidgins, Portuguese-based", u"Cree",
u"Crimean Tatar; Crimean Turkish", u"Creoles and pidgins", u"Kashubian", u"Cushitic languages",
u"Dakota", u"Dargwa",
u"Land Dayak languages", u"Delaware", u"Slave (Athapascan)", u"Dogrib",
u"Dinka", u"Divehi; Dhivehi; Maldivian", u"Dogri", u"Dravidian languages",
u"Lower Sorbian", u"Duala", u"Dutch, Middle (ca. 1050-1350)",
u"Dyula", u"Dzongkha", u"Efik", u"Egyptian (Ancient)",
u"Ekajuk", u"Elamite", u"English, Middle (1100-1500)",
u"Esperanto", u"Ewe", u"Ewondo",
u"Fang", u"Faroese", u"Fanti", u"Fijian",
u"Filipino; Pilipino", u"Finno-Ugrian languages", u"Fon",
u"French, Middle (ca. 1400-1600)", u"French, Old (842-ca. 1400)", u"Northern Frisian",
u"Eastern Frisian", u"Western Frisian", u"Fulah", u"Friulian",
u"Ga", u"Gayo", u"Gbaya", u"Germanic languages",
u"Georgian", u"Geez", u"Gilbertese",
u"Gaelic; Scottish Gaelic", u"Galician", u"Manx",
u"German, Middle High (ca. 1050-1500)", u"German, Old High (ca. 750-1050)", u"Gondi", u"Gorontalo",
u"Gothic", u"Grebo", u"Greek, Ancient (to 1453)",
u"Guarani", u"Swiss German; Alemannic; Alsatian", u"Gujarati", u"Gwich'in",
u"Haida", u"Haitian; Haitian Creole", u"Hausa", u"Hawaiian",
u"Hebrew", u"Herero", u"Hiligaynon", u"Himachali languages; Western Pahari languages",
u"Hindi", u"Hittite", u"Hmong; Mong", u"Hiri Motu",
u"Upper Sorbian", u"Hupa",
u"Iban", u"Igbo", u"Icelandic", u"Ido",
u"Sichuan Yi; Nuosu", u"Ijo languages", u"Inuktitut", u"Interlingue; Occidental",
u"Iloko", u"Interlingua (International Auxiliary Language Association)", u"Indic languages", u"Indonesian",
u"Indo-European languages", u"Ingush", u"Inupiaq", u"Iranian languages",
u"Iroquoian languages", u"Javanese", u"Lojban",
u"Japanese", u"Judeo-Persian", u"Judeo-Arabic", u"Kara-Kalpak",
u"Kabyle", u"Kachin; Jingpho", u"Kalaallisut; Greenlandic", u"Kamba",
u"Kannada", u"Karen languages", u"Kashmiri", u"Kanuri",
u"Kawi", u"Kazakh", u"Kabardian", u"Khasi",
u"Khoisan languages", u"Central Khmer", u"Khotanese;Sakan", u"Kikuyu; Gikuyu",
u"Kinyarwanda", u"Kirghiz; Kyrgyz", u"Kimbundu", u"Konkani",
u"Komi", u"Kongo", u"Korean", u"Kosraean",
u"Kpelle", u"Karachay-Balkar", u"Karelian", u"Kru languages",
u"Kurukh", u"Kuanyama; Kwanyama", u"Kumyk", u"Kurdish",
u"Kutenai", u"Ladino", u"Lahnda", u"Lamba",
u"Lao", u"Latin", u"Lezghian",
u"Limburgan; Limburger; Limburgish", u"Lingala", u"Mongo",
u"Lozi", u"Luxembourgish; Letzeburgesch", u"Luba-Lulua", u"Luba-Katanga",
u"Ganda", u"Luiseno", u"Lunda", u"Luo (Kenya and Tanzania)",
u"Lushai", u"Macedonian", u"Madurese", u"Magahi",
u"Marshallese", u"Maithili", u"Makasar", u"Malayalam",
u"Mandingo", u"Maori", u"Austronesian languages", u"Marathi",
u"Masai", u"Malay", u"Moksha", u"Mandar",
u"Mende", u"Irish, Middle (900-1200)", u"Mi'kmaq; Micmac", u"Minangkabau",
u"Uncoded languages", u"Mon-Khmer languages", u"Malagasy",
u"Manchu", u"Manipuri", u"Manobo languages", u"Mohawk",
u"Moldavian; Moldovan", u"Mongolian", u"Mossi", u"Multiple languages",
u"Munda languages", u"Creek", u"Mirandese", u"Marwari",
u"Mayan languages", u"Erzya", u"Nahuatl languages", u"North American Indian languages",
u"Neapolitan", u"Nauru", u"Navajo; Navaho", u"Ndebele, South; South Ndebele",
u"Ndebele, North; North Ndebele", u"Ndonga", u"Low German; Low Saxon; German, Low; Saxon, Low", u"Nepali",
u"Nepal Bhasa; Newari", u"Nias", u"Niger-Kordofanian languages", u"Niuean",
u"Norwegian Nynorsk; Nynorsk, Norwegian", u"Bokmål, Norwegian; Norwegian Bokmål", u"Nogai", u"Norse, Old",
u"Norwegian", u"N'Ko", u"Pedi; Sepedi; Northern Sotho", u"Nubian languages",
u"Classical Newari; Old Newari; Classical Nepal Bhasa", u"Chichewa; Chewa; Nyanja", u"Nyamwezi", u"Nyankole",
u"Nyoro", u"Nzima", u"Occitan (post 1500)", u"Ojibwa",
u"Oriya", u"Oromo", u"Osage", u"Ossetian; Ossetic",
u"Turkish, Ottoman (1500-1928)", u"Otomian languages", u"Papuan languages", u"Pangasinan",
u"Pahlavi", u"Pampanga; Kapampangan", u"Panjabi; Punjabi", u"Papiamento",
u"Palauan", u"Persian, Old (ca. 600-400 B.C.)", u"Persian", u"Philippine languages",
u"Phoenician", u"Pali", u"Pohnpeian",
u"Prakrit languages", u"Provençal, Old (to 1500); Occitan, Old (to 1500)", u"Pushto; Pashto",
u"Quechua", u"Rajasthani", u"Rapanui", u"Rarotongan; Cook Islands Maori",
u"Romance languages", u"Romansh", u"Romany",
u"Rundi", u"Aromanian; Arumanian; Macedo-Romanian", u"Russian", u"Sandawe",
u"Sango", u"Yakut", u"South American Indian languages", u"Salishan languages",
u"Samaritan Aramaic", u"Sanskrit", u"Sasak", u"Santali",
u"Sicilian", u"Scots", u"Selkup", u"Semitic languages",
u"Irish, Old (to 900)", u"Sign Languages", u"Shan", u"Sidamo",
u"Sinhala; Sinhalese", u"Siouan languages", u"Sino-Tibetan languages", u"Slavic languages",
u"Southern Sami", u"Northern Sami",
u"Sami languages", u"Lule Sami", u"Inari Sami", u"Samoan",
u"Skolt Sami", u"Shona", u"Sindhi", u"Soninke",
u"Sogdian", u"Somali", u"Songhai languages", u"Sotho, Southern",
u"Sardinian", u"Sranan Tongo", u"Serbian",
u"Serer", u"Nilo-Saharan languages", u"Swati", u"Sukuma",
u"Sundanese", u"Susu", u"Sumerian", u"Swahili",
u"Classical Syriac", u"Syriac", u"Tahitian",
u"Tai languages", u"Tamil", u"Tatar", u"Telugu",
u"Timne", u"Tereno", u"Tetum", u"Tajik",
u"Tagalog", u"Thai", u"Tibetan", u"Tigre",
u"Tigrinya", u"Tiv", u"Tokelau", u"Klingon; tlhIngan-Hol",
u"Tlingit", u"Tamashek", u"Tonga (Nyasa)", u"Tonga (Tonga Islands)",
u"Tok Pisin", u"Tsimshian", u"Tswana", u"Tsonga",
u"Turkmen", u"Tumbuka", u"Tupi languages", u"Turkish",
u"Altaic languages", u"Tuvalu", u"Twi", u"Tuvinian",
u"Udmurt", u"Ugaritic", u"Uighur; Uyghur", u"Ukrainian",
u"Umbundu", u"Undetermined", u"Urdu", u"Uzbek",
u"Vai", u"Venda", u"Vietnamese", u"Volapük",
u"Votic", u"Wakashan languages", u"Wolaitta; Wolaytta", u"Waray",
u"Washo", u"Welsh", u"Sorbian languages", u"Walloon",
u"Wolof", u"Kalmyk; Oirat", u"Xhosa", u"Yao",
u"Yapese", u"Yiddish", u"Yoruba", u"Yupik languages",
u"Zapotec", u"Blissymbols; Blissymbolics; Bliss", u"Zenaga", u"Standard Moroccan Tamazight",
u"Zhuang; Chuang", u"Zande languages", u"Zulu", u"Zuni",
u"Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki", u"other",
])


LANGUAGEID_TO_LANGUAGENAME = {}
LANGUAGEID_TO_LANGUAGENAME[u"aa"] = u"Afar"
LANGUAGEID_TO_LANGUAGENAME[u"ab"] = u"Abkhazian"
LANGUAGEID_TO_LANGUAGENAME[u"ace"] = u"Achinese"
LANGUAGEID_TO_LANGUAGENAME[u"ach"] = u"Acoli"
LANGUAGEID_TO_LANGUAGENAME[u"ada"] = u"Adangme"
LANGUAGEID_TO_LANGUAGENAME[u"ady"] = u"Adyghe; Adygei"
LANGUAGEID_TO_LANGUAGENAME[u"afa"] = u"Afro-Asiatic languages"
LANGUAGEID_TO_LANGUAGENAME[u"afh"] = u"Afrihili"
LANGUAGEID_TO_LANGUAGENAME[u"af"] = u"Afrikaans"
LANGUAGEID_TO_LANGUAGENAME[u"ain"] = u"Ainu"
LANGUAGEID_TO_LANGUAGENAME[u"ak"] = u"Akan"
LANGUAGEID_TO_LANGUAGENAME[u"akk"] = u"Akkadian"
LANGUAGEID_TO_LANGUAGENAME[u"sq"] = u"Albanian"
LANGUAGEID_TO_LANGUAGENAME[u"ale"] = u"Aleut"
LANGUAGEID_TO_LANGUAGENAME[u"alg"] = u"Algonquian languages"
LANGUAGEID_TO_LANGUAGENAME[u"alt"] = u"Southern Altai"
LANGUAGEID_TO_LANGUAGENAME[u"am"] = u"Amharic"
LANGUAGEID_TO_LANGUAGENAME[u"ang"] = u"English, Old (ca. 450-1100)"
LANGUAGEID_TO_LANGUAGENAME[u"anp"] = u"Angika"
LANGUAGEID_TO_LANGUAGENAME[u"apa"] = u"Apache languages"
LANGUAGEID_TO_LANGUAGENAME[u"ar"] = u"Arabic"
LANGUAGEID_TO_LANGUAGENAME[u"arc"] = u"Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"
LANGUAGEID_TO_LANGUAGENAME[u"an"] = u"Aragonese"
LANGUAGEID_TO_LANGUAGENAME[u"hy"] = u"Armenian"
LANGUAGEID_TO_LANGUAGENAME[u"arn"] = u"Mapudungun; Mapuche"
LANGUAGEID_TO_LANGUAGENAME[u"arp"] = u"Arapaho"
LANGUAGEID_TO_LANGUAGENAME[u"art"] = u"Artificial languages"
LANGUAGEID_TO_LANGUAGENAME[u"arw"] = u"Arawak"
LANGUAGEID_TO_LANGUAGENAME[u"as"] = u"Assamese"
LANGUAGEID_TO_LANGUAGENAME[u"ast"] = u"Asturian; Bable; Leonese; Asturleonese"
LANGUAGEID_TO_LANGUAGENAME[u"ath"] = u"Athapascan languages"
LANGUAGEID_TO_LANGUAGENAME[u"aus"] = u"Australian languages"
LANGUAGEID_TO_LANGUAGENAME[u"av"] = u"Avaric"
LANGUAGEID_TO_LANGUAGENAME[u"ae"] = u"Avestan"
LANGUAGEID_TO_LANGUAGENAME[u"awa"] = u"Awadhi"
LANGUAGEID_TO_LANGUAGENAME[u"ay"] = u"Aymara"
LANGUAGEID_TO_LANGUAGENAME[u"az"] = u"Azerbaijani"
LANGUAGEID_TO_LANGUAGENAME[u"bad"] = u"Banda languages"
LANGUAGEID_TO_LANGUAGENAME[u"bai"] = u"Bamileke languages"
LANGUAGEID_TO_LANGUAGENAME[u"ba"] = u"Bashkir"
LANGUAGEID_TO_LANGUAGENAME[u"bal"] = u"Baluchi"
LANGUAGEID_TO_LANGUAGENAME[u"bm"] = u"Bambara"
LANGUAGEID_TO_LANGUAGENAME[u"ban"] = u"Balinese"
LANGUAGEID_TO_LANGUAGENAME[u"eu"] = u"Basque"
LANGUAGEID_TO_LANGUAGENAME[u"bas"] = u"Basa"
LANGUAGEID_TO_LANGUAGENAME[u"bat"] = u"Baltic languages"
LANGUAGEID_TO_LANGUAGENAME[u"bej"] = u"Beja; Bedawiyet"
LANGUAGEID_TO_LANGUAGENAME[u"be"] = u"Belarusian"
LANGUAGEID_TO_LANGUAGENAME[u"bem"] = u"Bemba"
LANGUAGEID_TO_LANGUAGENAME[u"bn"] = u"Bengali"
LANGUAGEID_TO_LANGUAGENAME[u"ber"] = u"Berber languages"
LANGUAGEID_TO_LANGUAGENAME[u"bho"] = u"Bhojpuri"
LANGUAGEID_TO_LANGUAGENAME[u"bh"] = u"Bihari languages"
LANGUAGEID_TO_LANGUAGENAME[u"bik"] = u"Bikol"
LANGUAGEID_TO_LANGUAGENAME[u"bin"] = u"Bini; Edo"
LANGUAGEID_TO_LANGUAGENAME[u"bi"] = u"Bislama"
LANGUAGEID_TO_LANGUAGENAME[u"bla"] = u"Siksika"
LANGUAGEID_TO_LANGUAGENAME[u"bnt"] = u"Bantu languages"
LANGUAGEID_TO_LANGUAGENAME[u"bs"] = u"Bosnian"
LANGUAGEID_TO_LANGUAGENAME[u"bra"] = u"Braj"
LANGUAGEID_TO_LANGUAGENAME[u"br"] = u"Breton"
LANGUAGEID_TO_LANGUAGENAME[u"btk"] = u"Batak languages"
LANGUAGEID_TO_LANGUAGENAME[u"bua"] = u"Buriat"
LANGUAGEID_TO_LANGUAGENAME[u"bug"] = u"Buginese"
LANGUAGEID_TO_LANGUAGENAME[u"bg"] = u"Bulgarian"
LANGUAGEID_TO_LANGUAGENAME[u"my"] = u"Burmese"
LANGUAGEID_TO_LANGUAGENAME[u"byn"] = u"Blin; Bilin"
LANGUAGEID_TO_LANGUAGENAME[u"cad"] = u"Caddo"
LANGUAGEID_TO_LANGUAGENAME[u"cai"] = u"Central American Indian languages"
LANGUAGEID_TO_LANGUAGENAME[u"car"] = u"Galibi Carib"
LANGUAGEID_TO_LANGUAGENAME[u"ca"] = u"Catalan; Valencian"
LANGUAGEID_TO_LANGUAGENAME[u"cau"] = u"Caucasian languages"
LANGUAGEID_TO_LANGUAGENAME[u"ceb"] = u"Cebuano"
LANGUAGEID_TO_LANGUAGENAME[u"cel"] = u"Celtic languages"
LANGUAGEID_TO_LANGUAGENAME[u"ch"] = u"Chamorro"
LANGUAGEID_TO_LANGUAGENAME[u"chb"] = u"Chibcha"
LANGUAGEID_TO_LANGUAGENAME[u"ce"] = u"Chechen"
LANGUAGEID_TO_LANGUAGENAME[u"chg"] = u"Chagatai"
LANGUAGEID_TO_LANGUAGENAME[u"zh"] = u"Chinese"
LANGUAGEID_TO_LANGUAGENAME[u"chk"] = u"Chuukese"
LANGUAGEID_TO_LANGUAGENAME[u"chm"] = u"Mari"
LANGUAGEID_TO_LANGUAGENAME[u"chn"] = u"Chinook jargon"
LANGUAGEID_TO_LANGUAGENAME[u"cho"] = u"Choctaw"
LANGUAGEID_TO_LANGUAGENAME[u"chp"] = u"Chipewyan; Dene Suline"
LANGUAGEID_TO_LANGUAGENAME[u"chr"] = u"Cherokee"
LANGUAGEID_TO_LANGUAGENAME[u"cu"] = u"Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"
LANGUAGEID_TO_LANGUAGENAME[u"cv"] = u"Chuvash"
LANGUAGEID_TO_LANGUAGENAME[u"chy"] = u"Cheyenne"
LANGUAGEID_TO_LANGUAGENAME[u"cmc"] = u"Chamic languages"
LANGUAGEID_TO_LANGUAGENAME[u"cop"] = u"Coptic"
LANGUAGEID_TO_LANGUAGENAME[u"kw"] = u"Cornish"
LANGUAGEID_TO_LANGUAGENAME[u"co"] = u"Corsican"
LANGUAGEID_TO_LANGUAGENAME[u"cpe"] = u"Creoles and pidgins, English based"
LANGUAGEID_TO_LANGUAGENAME[u"cpf"] = u"Creoles and pidgins, French-based"
LANGUAGEID_TO_LANGUAGENAME[u"cpp"] = u"Creoles and pidgins, Portuguese-based"
LANGUAGEID_TO_LANGUAGENAME[u"cr"] = u"Cree"
LANGUAGEID_TO_LANGUAGENAME[u"crh"] = u"Crimean Tatar; Crimean Turkish"
LANGUAGEID_TO_LANGUAGENAME[u"crp"] = u"Creoles and pidgins"
LANGUAGEID_TO_LANGUAGENAME[u"csb"] = u"Kashubian"
LANGUAGEID_TO_LANGUAGENAME[u"cus"] = u"Cushitic languages"
LANGUAGEID_TO_LANGUAGENAME[u"cs"] = u"Czech"
LANGUAGEID_TO_LANGUAGENAME[u"dak"] = u"Dakota"
LANGUAGEID_TO_LANGUAGENAME[u"da"] = u"Danish"
LANGUAGEID_TO_LANGUAGENAME[u"dar"] = u"Dargwa"
LANGUAGEID_TO_LANGUAGENAME[u"day"] = u"Land Dayak languages"
LANGUAGEID_TO_LANGUAGENAME[u"del"] = u"Delaware"
LANGUAGEID_TO_LANGUAGENAME[u"den"] = u"Slave (Athapascan)"
LANGUAGEID_TO_LANGUAGENAME[u"dgr"] = u"Dogrib"
LANGUAGEID_TO_LANGUAGENAME[u"din"] = u"Dinka"
LANGUAGEID_TO_LANGUAGENAME[u"dv"] = u"Divehi; Dhivehi; Maldivian"
LANGUAGEID_TO_LANGUAGENAME[u"doi"] = u"Dogri"
LANGUAGEID_TO_LANGUAGENAME[u"dra"] = u"Dravidian languages"
LANGUAGEID_TO_LANGUAGENAME[u"dsb"] = u"Lower Sorbian"
LANGUAGEID_TO_LANGUAGENAME[u"dua"] = u"Duala"
LANGUAGEID_TO_LANGUAGENAME[u"dum"] = u"Dutch, Middle (ca. 1050-1350)"
LANGUAGEID_TO_LANGUAGENAME[u"nl"] = u"Dutch; Flemish"
LANGUAGEID_TO_LANGUAGENAME[u"dyu"] = u"Dyula"
LANGUAGEID_TO_LANGUAGENAME[u"dz"] = u"Dzongkha"
LANGUAGEID_TO_LANGUAGENAME[u"efi"] = u"Efik"
LANGUAGEID_TO_LANGUAGENAME[u"egy"] = u"Egyptian (Ancient)"
LANGUAGEID_TO_LANGUAGENAME[u"eka"] = u"Ekajuk"
LANGUAGEID_TO_LANGUAGENAME[u"elx"] = u"Elamite"
LANGUAGEID_TO_LANGUAGENAME[u"en"] = u"English"
LANGUAGEID_TO_LANGUAGENAME[u"enm"] = u"English, Middle (1100-1500)"
LANGUAGEID_TO_LANGUAGENAME[u"eo"] = u"Esperanto"
LANGUAGEID_TO_LANGUAGENAME[u"et"] = u"Estonian"
LANGUAGEID_TO_LANGUAGENAME[u"ee"] = u"Ewe"
LANGUAGEID_TO_LANGUAGENAME[u"ewo"] = u"Ewondo"
LANGUAGEID_TO_LANGUAGENAME[u"fan"] = u"Fang"
LANGUAGEID_TO_LANGUAGENAME[u"fo"] = u"Faroese"
LANGUAGEID_TO_LANGUAGENAME[u"fat"] = u"Fanti"
LANGUAGEID_TO_LANGUAGENAME[u"fj"] = u"Fijian"
LANGUAGEID_TO_LANGUAGENAME[u"fil"] = u"Filipino; Pilipino"
LANGUAGEID_TO_LANGUAGENAME[u"fi"] = u"Finnish"
LANGUAGEID_TO_LANGUAGENAME[u"fiu"] = u"Finno-Ugrian languages"
LANGUAGEID_TO_LANGUAGENAME[u"fon"] = u"Fon"
LANGUAGEID_TO_LANGUAGENAME[u"fr"] = u"French"
LANGUAGEID_TO_LANGUAGENAME[u"frm"] = u"French, Middle (ca. 1400-1600)"
LANGUAGEID_TO_LANGUAGENAME[u"fro"] = u"French, Old (842-ca. 1400)"
LANGUAGEID_TO_LANGUAGENAME[u"frr"] = u"Northern Frisian"
LANGUAGEID_TO_LANGUAGENAME[u"frs"] = u"Eastern Frisian"
LANGUAGEID_TO_LANGUAGENAME[u"fy"] = u"Western Frisian"
LANGUAGEID_TO_LANGUAGENAME[u"ff"] = u"Fulah"
LANGUAGEID_TO_LANGUAGENAME[u"fur"] = u"Friulian"
LANGUAGEID_TO_LANGUAGENAME[u"gaa"] = u"Ga"
LANGUAGEID_TO_LANGUAGENAME[u"gay"] = u"Gayo"
LANGUAGEID_TO_LANGUAGENAME[u"gba"] = u"Gbaya"
LANGUAGEID_TO_LANGUAGENAME[u"gem"] = u"Germanic languages"
LANGUAGEID_TO_LANGUAGENAME[u"ka"] = u"Georgian"
LANGUAGEID_TO_LANGUAGENAME[u"de"] = u"German"
LANGUAGEID_TO_LANGUAGENAME[u"gez"] = u"Geez"
LANGUAGEID_TO_LANGUAGENAME[u"gil"] = u"Gilbertese"
LANGUAGEID_TO_LANGUAGENAME[u"gd"] = u"Gaelic; Scottish Gaelic"
LANGUAGEID_TO_LANGUAGENAME[u"ga"] = u"Irish"
LANGUAGEID_TO_LANGUAGENAME[u"gl"] = u"Galician"
LANGUAGEID_TO_LANGUAGENAME[u"gv"] = u"Manx"
LANGUAGEID_TO_LANGUAGENAME[u"gmh"] = u"German, Middle High (ca. 1050-1500)"
LANGUAGEID_TO_LANGUAGENAME[u"goh"] = u"German, Old High (ca. 750-1050)"
LANGUAGEID_TO_LANGUAGENAME[u"gon"] = u"Gondi"
LANGUAGEID_TO_LANGUAGENAME[u"gor"] = u"Gorontalo"
LANGUAGEID_TO_LANGUAGENAME[u"got"] = u"Gothic"
LANGUAGEID_TO_LANGUAGENAME[u"grb"] = u"Grebo"
LANGUAGEID_TO_LANGUAGENAME[u"grc"] = u"Greek, Ancient (to 1453)"
LANGUAGEID_TO_LANGUAGENAME[u"el"] = u"Greek, Modern (1453-)"
LANGUAGEID_TO_LANGUAGENAME[u"gn"] = u"Guarani"
LANGUAGEID_TO_LANGUAGENAME[u"gsw"] = u"Swiss German; Alemannic; Alsatian"
LANGUAGEID_TO_LANGUAGENAME[u"gu"] = u"Gujarati"
LANGUAGEID_TO_LANGUAGENAME[u"gwi"] = u"Gwich'in"
LANGUAGEID_TO_LANGUAGENAME[u"hai"] = u"Haida"
LANGUAGEID_TO_LANGUAGENAME[u"ht"] = u"Haitian; Haitian Creole"
LANGUAGEID_TO_LANGUAGENAME[u"ha"] = u"Hausa"
LANGUAGEID_TO_LANGUAGENAME[u"haw"] = u"Hawaiian"
LANGUAGEID_TO_LANGUAGENAME[u"he"] = u"Hebrew"
LANGUAGEID_TO_LANGUAGENAME[u"hz"] = u"Herero"
LANGUAGEID_TO_LANGUAGENAME[u"hil"] = u"Hiligaynon"
LANGUAGEID_TO_LANGUAGENAME[u"him"] = u"Himachali languages; Western Pahari languages"
LANGUAGEID_TO_LANGUAGENAME[u"hi"] = u"Hindi"
LANGUAGEID_TO_LANGUAGENAME[u"hit"] = u"Hittite"
LANGUAGEID_TO_LANGUAGENAME[u"hmn"] = u"Hmong; Mong"
LANGUAGEID_TO_LANGUAGENAME[u"ho"] = u"Hiri Motu"
LANGUAGEID_TO_LANGUAGENAME[u"hr"] = u"Croatian"
LANGUAGEID_TO_LANGUAGENAME[u"hsb"] = u"Upper Sorbian"
LANGUAGEID_TO_LANGUAGENAME[u"hu"] = u"Hungarian"
LANGUAGEID_TO_LANGUAGENAME[u"hup"] = u"Hupa"
LANGUAGEID_TO_LANGUAGENAME[u"iba"] = u"Iban"
LANGUAGEID_TO_LANGUAGENAME[u"ig"] = u"Igbo"
LANGUAGEID_TO_LANGUAGENAME[u"is"] = u"Icelandic"
LANGUAGEID_TO_LANGUAGENAME[u"io"] = u"Ido"
LANGUAGEID_TO_LANGUAGENAME[u"ii"] = u"Sichuan Yi; Nuosu"
LANGUAGEID_TO_LANGUAGENAME[u"ijo"] = u"Ijo languages"
LANGUAGEID_TO_LANGUAGENAME[u"iu"] = u"Inuktitut"
LANGUAGEID_TO_LANGUAGENAME[u"ie"] = u"Interlingue; Occidental"
LANGUAGEID_TO_LANGUAGENAME[u"ilo"] = u"Iloko"
LANGUAGEID_TO_LANGUAGENAME[u"ia"] = u"Interlingua (International Auxiliary Language Association)"
LANGUAGEID_TO_LANGUAGENAME[u"inc"] = u"Indic languages"
LANGUAGEID_TO_LANGUAGENAME[u"id"] = u"Indonesian"
LANGUAGEID_TO_LANGUAGENAME[u"ine"] = u"Indo-European languages"
LANGUAGEID_TO_LANGUAGENAME[u"inh"] = u"Ingush"
LANGUAGEID_TO_LANGUAGENAME[u"ik"] = u"Inupiaq"
LANGUAGEID_TO_LANGUAGENAME[u"ira"] = u"Iranian languages"
LANGUAGEID_TO_LANGUAGENAME[u"iro"] = u"Iroquoian languages"
LANGUAGEID_TO_LANGUAGENAME[u"it"] = u"Italian"
LANGUAGEID_TO_LANGUAGENAME[u"jv"] = u"Javanese"
LANGUAGEID_TO_LANGUAGENAME[u"jbo"] = u"Lojban"
LANGUAGEID_TO_LANGUAGENAME[u"ja"] = u"Japanese"
LANGUAGEID_TO_LANGUAGENAME[u"jpr"] = u"Judeo-Persian"
LANGUAGEID_TO_LANGUAGENAME[u"jrb"] = u"Judeo-Arabic"
LANGUAGEID_TO_LANGUAGENAME[u"kaa"] = u"Kara-Kalpak"
LANGUAGEID_TO_LANGUAGENAME[u"kab"] = u"Kabyle"
LANGUAGEID_TO_LANGUAGENAME[u"kac"] = u"Kachin; Jingpho"
LANGUAGEID_TO_LANGUAGENAME[u"kl"] = u"Kalaallisut; Greenlandic"
LANGUAGEID_TO_LANGUAGENAME[u"kam"] = u"Kamba"
LANGUAGEID_TO_LANGUAGENAME[u"kn"] = u"Kannada"
LANGUAGEID_TO_LANGUAGENAME[u"kar"] = u"Karen languages"
LANGUAGEID_TO_LANGUAGENAME[u"ks"] = u"Kashmiri"
LANGUAGEID_TO_LANGUAGENAME[u"kr"] = u"Kanuri"
LANGUAGEID_TO_LANGUAGENAME[u"kaw"] = u"Kawi"
LANGUAGEID_TO_LANGUAGENAME[u"kk"] = u"Kazakh"
LANGUAGEID_TO_LANGUAGENAME[u"kbd"] = u"Kabardian"
LANGUAGEID_TO_LANGUAGENAME[u"kha"] = u"Khasi"
LANGUAGEID_TO_LANGUAGENAME[u"khi"] = u"Khoisan languages"
LANGUAGEID_TO_LANGUAGENAME[u"km"] = u"Central Khmer"
LANGUAGEID_TO_LANGUAGENAME[u"kho"] = u"Khotanese;Sakan"
LANGUAGEID_TO_LANGUAGENAME[u"ki"] = u"Kikuyu; Gikuyu"
LANGUAGEID_TO_LANGUAGENAME[u"rw"] = u"Kinyarwanda"
LANGUAGEID_TO_LANGUAGENAME[u"ky"] = u"Kirghiz; Kyrgyz"
LANGUAGEID_TO_LANGUAGENAME[u"kmb"] = u"Kimbundu"
LANGUAGEID_TO_LANGUAGENAME[u"kok"] = u"Konkani"
LANGUAGEID_TO_LANGUAGENAME[u"kv"] = u"Komi"
LANGUAGEID_TO_LANGUAGENAME[u"kg"] = u"Kongo"
LANGUAGEID_TO_LANGUAGENAME[u"ko"] = u"Korean"
LANGUAGEID_TO_LANGUAGENAME[u"kos"] = u"Kosraean"
LANGUAGEID_TO_LANGUAGENAME[u"kpe"] = u"Kpelle"
LANGUAGEID_TO_LANGUAGENAME[u"krc"] = u"Karachay-Balkar"
LANGUAGEID_TO_LANGUAGENAME[u"krl"] = u"Karelian"
LANGUAGEID_TO_LANGUAGENAME[u"kro"] = u"Kru languages"
LANGUAGEID_TO_LANGUAGENAME[u"kru"] = u"Kurukh"
LANGUAGEID_TO_LANGUAGENAME[u"kj"] = u"Kuanyama; Kwanyama"
LANGUAGEID_TO_LANGUAGENAME[u"kum"] = u"Kumyk"
LANGUAGEID_TO_LANGUAGENAME[u"ku"] = u"Kurdish"
LANGUAGEID_TO_LANGUAGENAME[u"kut"] = u"Kutenai"
LANGUAGEID_TO_LANGUAGENAME[u"lad"] = u"Ladino"
LANGUAGEID_TO_LANGUAGENAME[u"lah"] = u"Lahnda"
LANGUAGEID_TO_LANGUAGENAME[u"lam"] = u"Lamba"
LANGUAGEID_TO_LANGUAGENAME[u"lo"] = u"Lao"
LANGUAGEID_TO_LANGUAGENAME[u"la"] = u"Latin"
LANGUAGEID_TO_LANGUAGENAME[u"lv"] = u"Latvian"
LANGUAGEID_TO_LANGUAGENAME[u"lez"] = u"Lezghian"
LANGUAGEID_TO_LANGUAGENAME[u"li"] = u"Limburgan; Limburger; Limburgish"
LANGUAGEID_TO_LANGUAGENAME[u"ln"] = u"Lingala"
LANGUAGEID_TO_LANGUAGENAME[u"lt"] = u"Lithuanian"
LANGUAGEID_TO_LANGUAGENAME[u"lol"] = u"Mongo"
LANGUAGEID_TO_LANGUAGENAME[u"loz"] = u"Lozi"
LANGUAGEID_TO_LANGUAGENAME[u"lb"] = u"Luxembourgish; Letzeburgesch"
LANGUAGEID_TO_LANGUAGENAME[u"lua"] = u"Luba-Lulua"
LANGUAGEID_TO_LANGUAGENAME[u"lu"] = u"Luba-Katanga"
LANGUAGEID_TO_LANGUAGENAME[u"lg"] = u"Ganda"
LANGUAGEID_TO_LANGUAGENAME[u"lui"] = u"Luiseno"
LANGUAGEID_TO_LANGUAGENAME[u"lun"] = u"Lunda"
LANGUAGEID_TO_LANGUAGENAME[u"luo"] = u"Luo (Kenya and Tanzania)"
LANGUAGEID_TO_LANGUAGENAME[u"lus"] = u"Lushai"
LANGUAGEID_TO_LANGUAGENAME[u"mk"] = u"Macedonian"
LANGUAGEID_TO_LANGUAGENAME[u"mad"] = u"Madurese"
LANGUAGEID_TO_LANGUAGENAME[u"mag"] = u"Magahi"
LANGUAGEID_TO_LANGUAGENAME[u"mh"] = u"Marshallese"
LANGUAGEID_TO_LANGUAGENAME[u"mai"] = u"Maithili"
LANGUAGEID_TO_LANGUAGENAME[u"mak"] = u"Makasar"
LANGUAGEID_TO_LANGUAGENAME[u"ml"] = u"Malayalam"
LANGUAGEID_TO_LANGUAGENAME[u"man"] = u"Mandingo"
LANGUAGEID_TO_LANGUAGENAME[u"mi"] = u"Maori"
LANGUAGEID_TO_LANGUAGENAME[u"map"] = u"Austronesian languages"
LANGUAGEID_TO_LANGUAGENAME[u"mr"] = u"Marathi"
LANGUAGEID_TO_LANGUAGENAME[u"mas"] = u"Masai"
LANGUAGEID_TO_LANGUAGENAME[u"ms"] = u"Malay"
LANGUAGEID_TO_LANGUAGENAME[u"mdf"] = u"Moksha"
LANGUAGEID_TO_LANGUAGENAME[u"mdr"] = u"Mandar"
LANGUAGEID_TO_LANGUAGENAME[u"men"] = u"Mende"
LANGUAGEID_TO_LANGUAGENAME[u"mga"] = u"Irish, Middle (900-1200)"
LANGUAGEID_TO_LANGUAGENAME[u"mic"] = u"Mi'kmaq; Micmac"
LANGUAGEID_TO_LANGUAGENAME[u"min"] = u"Minangkabau"
LANGUAGEID_TO_LANGUAGENAME[u"mis"] = u"Uncoded languages"
LANGUAGEID_TO_LANGUAGENAME[u"mkh"] = u"Mon-Khmer languages"
LANGUAGEID_TO_LANGUAGENAME[u"mg"] = u"Malagasy"
LANGUAGEID_TO_LANGUAGENAME[u"mt"] = u"Maltese"
LANGUAGEID_TO_LANGUAGENAME[u"mnc"] = u"Manchu"
LANGUAGEID_TO_LANGUAGENAME[u"mni"] = u"Manipuri"
LANGUAGEID_TO_LANGUAGENAME[u"mno"] = u"Manobo languages"
LANGUAGEID_TO_LANGUAGENAME[u"moh"] = u"Mohawk"
LANGUAGEID_TO_LANGUAGENAME[u"mo"] = u"Moldavian; Moldovan"
LANGUAGEID_TO_LANGUAGENAME[u"mn"] = u"Mongolian"
LANGUAGEID_TO_LANGUAGENAME[u"mos"] = u"Mossi"
LANGUAGEID_TO_LANGUAGENAME[u"mul"] = u"Multiple languages"
LANGUAGEID_TO_LANGUAGENAME[u"mun"] = u"Munda languages"
LANGUAGEID_TO_LANGUAGENAME[u"mus"] = u"Creek"
LANGUAGEID_TO_LANGUAGENAME[u"mwl"] = u"Mirandese"
LANGUAGEID_TO_LANGUAGENAME[u"mwr"] = u"Marwari"
LANGUAGEID_TO_LANGUAGENAME[u"myn"] = u"Mayan languages"
LANGUAGEID_TO_LANGUAGENAME[u"myv"] = u"Erzya"
LANGUAGEID_TO_LANGUAGENAME[u"nah"] = u"Nahuatl languages"
LANGUAGEID_TO_LANGUAGENAME[u"nai"] = u"North American Indian languages"
LANGUAGEID_TO_LANGUAGENAME[u"nap"] = u"Neapolitan"
LANGUAGEID_TO_LANGUAGENAME[u"na"] = u"Nauru"
LANGUAGEID_TO_LANGUAGENAME[u"nv"] = u"Navajo; Navaho"
LANGUAGEID_TO_LANGUAGENAME[u"nr"] = u"Ndebele, South; South Ndebele"
LANGUAGEID_TO_LANGUAGENAME[u"nd"] = u"Ndebele, North; North Ndebele"
LANGUAGEID_TO_LANGUAGENAME[u"ng"] = u"Ndonga"
LANGUAGEID_TO_LANGUAGENAME[u"nds"] = u"Low German; Low Saxon; German, Low; Saxon, Low"
LANGUAGEID_TO_LANGUAGENAME[u"ne"] = u"Nepali"
LANGUAGEID_TO_LANGUAGENAME[u"new"] = u"Nepal Bhasa; Newari"
LANGUAGEID_TO_LANGUAGENAME[u"nia"] = u"Nias"
LANGUAGEID_TO_LANGUAGENAME[u"nic"] = u"Niger-Kordofanian languages"
LANGUAGEID_TO_LANGUAGENAME[u"niu"] = u"Niuean"
LANGUAGEID_TO_LANGUAGENAME[u"nn"] = u"Norwegian Nynorsk; Nynorsk, Norwegian"
LANGUAGEID_TO_LANGUAGENAME[u"nb"] = u"Bokmål, Norwegian; Norwegian Bokmål"
LANGUAGEID_TO_LANGUAGENAME[u"nog"] = u"Nogai"
LANGUAGEID_TO_LANGUAGENAME[u"non"] = u"Norse, Old"
LANGUAGEID_TO_LANGUAGENAME[u"no"] = u"Norwegian"
LANGUAGEID_TO_LANGUAGENAME[u"nqo"] = u"N'Ko"
LANGUAGEID_TO_LANGUAGENAME[u"nso"] = u"Pedi; Sepedi; Northern Sotho"
LANGUAGEID_TO_LANGUAGENAME[u"nub"] = u"Nubian languages"
LANGUAGEID_TO_LANGUAGENAME[u"nwc"] = u"Classical Newari; Old Newari; Classical Nepal Bhasa"
LANGUAGEID_TO_LANGUAGENAME[u"ny"] = u"Chichewa; Chewa; Nyanja"
LANGUAGEID_TO_LANGUAGENAME[u"nym"] = u"Nyamwezi"
LANGUAGEID_TO_LANGUAGENAME[u"nyn"] = u"Nyankole"
LANGUAGEID_TO_LANGUAGENAME[u"nyo"] = u"Nyoro"
LANGUAGEID_TO_LANGUAGENAME[u"nzi"] = u"Nzima"
LANGUAGEID_TO_LANGUAGENAME[u"oc"] = u"Occitan (post 1500)"
LANGUAGEID_TO_LANGUAGENAME[u"oj"] = u"Ojibwa"
LANGUAGEID_TO_LANGUAGENAME[u"or"] = u"Oriya"
LANGUAGEID_TO_LANGUAGENAME[u"om"] = u"Oromo"
LANGUAGEID_TO_LANGUAGENAME[u"osa"] = u"Osage"
LANGUAGEID_TO_LANGUAGENAME[u"os"] = u"Ossetian; Ossetic"
LANGUAGEID_TO_LANGUAGENAME[u"ota"] = u"Turkish, Ottoman (1500-1928)"
LANGUAGEID_TO_LANGUAGENAME[u"other"] = u"other"
LANGUAGEID_TO_LANGUAGENAME[u"oto"] = u"Otomian languages"
LANGUAGEID_TO_LANGUAGENAME[u"paa"] = u"Papuan languages"
LANGUAGEID_TO_LANGUAGENAME[u"pag"] = u"Pangasinan"
LANGUAGEID_TO_LANGUAGENAME[u"pal"] = u"Pahlavi"
LANGUAGEID_TO_LANGUAGENAME[u"pam"] = u"Pampanga; Kapampangan"
LANGUAGEID_TO_LANGUAGENAME[u"pa"] = u"Panjabi; Punjabi"
LANGUAGEID_TO_LANGUAGENAME[u"pap"] = u"Papiamento"
LANGUAGEID_TO_LANGUAGENAME[u"pau"] = u"Palauan"
LANGUAGEID_TO_LANGUAGENAME[u"peo"] = u"Persian, Old (ca. 600-400 B.C.)"
LANGUAGEID_TO_LANGUAGENAME[u"fa"] = u"Persian"
LANGUAGEID_TO_LANGUAGENAME[u"phi"] = u"Philippine languages"
LANGUAGEID_TO_LANGUAGENAME[u"phn"] = u"Phoenician"
LANGUAGEID_TO_LANGUAGENAME[u"pi"] = u"Pali"
LANGUAGEID_TO_LANGUAGENAME[u"pl"] = u"Polish"
LANGUAGEID_TO_LANGUAGENAME[u"pon"] = u"Pohnpeian"
LANGUAGEID_TO_LANGUAGENAME[u"pt"] = u"Portuguese"
LANGUAGEID_TO_LANGUAGENAME[u"pra"] = u"Prakrit languages"
LANGUAGEID_TO_LANGUAGENAME[u"pro"] = u"Provençal, Old (to 1500); Occitan, Old (to 1500)"
LANGUAGEID_TO_LANGUAGENAME[u"ps"] = u"Pushto; Pashto"
LANGUAGEID_TO_LANGUAGENAME[u"qu"] = u"Quechua"
LANGUAGEID_TO_LANGUAGENAME[u"raj"] = u"Rajasthani"
LANGUAGEID_TO_LANGUAGENAME[u"rap"] = u"Rapanui"
LANGUAGEID_TO_LANGUAGENAME[u"rar"] = u"Rarotongan; Cook Islands Maori"
LANGUAGEID_TO_LANGUAGENAME[u"roa"] = u"Romance languages"
LANGUAGEID_TO_LANGUAGENAME[u"rm"] = u"Romansh"
LANGUAGEID_TO_LANGUAGENAME[u"rom"] = u"Romany"
LANGUAGEID_TO_LANGUAGENAME[u"ro"] = u"Romanian"
LANGUAGEID_TO_LANGUAGENAME[u"rn"] = u"Rundi"
LANGUAGEID_TO_LANGUAGENAME[u"rup"] = u"Aromanian; Arumanian; Macedo-Romanian"
LANGUAGEID_TO_LANGUAGENAME[u"ru"] = u"Russian"
LANGUAGEID_TO_LANGUAGENAME[u"sad"] = u"Sandawe"
LANGUAGEID_TO_LANGUAGENAME[u"sg"] = u"Sango"
LANGUAGEID_TO_LANGUAGENAME[u"sah"] = u"Yakut"
LANGUAGEID_TO_LANGUAGENAME[u"sai"] = u"South American Indian languages"
LANGUAGEID_TO_LANGUAGENAME[u"sal"] = u"Salishan languages"
LANGUAGEID_TO_LANGUAGENAME[u"sam"] = u"Samaritan Aramaic"
LANGUAGEID_TO_LANGUAGENAME[u"sa"] = u"Sanskrit"
LANGUAGEID_TO_LANGUAGENAME[u"sas"] = u"Sasak"
LANGUAGEID_TO_LANGUAGENAME[u"sat"] = u"Santali"
LANGUAGEID_TO_LANGUAGENAME[u"scn"] = u"Sicilian"
LANGUAGEID_TO_LANGUAGENAME[u"sco"] = u"Scots"
LANGUAGEID_TO_LANGUAGENAME[u"sel"] = u"Selkup"
LANGUAGEID_TO_LANGUAGENAME[u"sem"] = u"Semitic languages"
LANGUAGEID_TO_LANGUAGENAME[u"sga"] = u"Irish, Old (to 900)"
LANGUAGEID_TO_LANGUAGENAME[u"sgn"] = u"Sign Languages"
LANGUAGEID_TO_LANGUAGENAME[u"shn"] = u"Shan"
LANGUAGEID_TO_LANGUAGENAME[u"sid"] = u"Sidamo"
LANGUAGEID_TO_LANGUAGENAME[u"si"] = u"Sinhala; Sinhalese"
LANGUAGEID_TO_LANGUAGENAME[u"sio"] = u"Siouan languages"
LANGUAGEID_TO_LANGUAGENAME[u"sit"] = u"Sino-Tibetan languages"
LANGUAGEID_TO_LANGUAGENAME[u"sla"] = u"Slavic languages"
LANGUAGEID_TO_LANGUAGENAME[u"sk"] = u"Slovak"
LANGUAGEID_TO_LANGUAGENAME[u"sl"] = u"Slovenian"
LANGUAGEID_TO_LANGUAGENAME[u"sma"] = u"Southern Sami"
LANGUAGEID_TO_LANGUAGENAME[u"se"] = u"Northern Sami"
LANGUAGEID_TO_LANGUAGENAME[u"smi"] = u"Sami languages"
LANGUAGEID_TO_LANGUAGENAME[u"smj"] = u"Lule Sami"
LANGUAGEID_TO_LANGUAGENAME[u"smn"] = u"Inari Sami"
LANGUAGEID_TO_LANGUAGENAME[u"sm"] = u"Samoan"
LANGUAGEID_TO_LANGUAGENAME[u"sms"] = u"Skolt Sami"
LANGUAGEID_TO_LANGUAGENAME[u"sn"] = u"Shona"
LANGUAGEID_TO_LANGUAGENAME[u"sd"] = u"Sindhi"
LANGUAGEID_TO_LANGUAGENAME[u"snk"] = u"Soninke"
LANGUAGEID_TO_LANGUAGENAME[u"sog"] = u"Sogdian"
LANGUAGEID_TO_LANGUAGENAME[u"so"] = u"Somali"
LANGUAGEID_TO_LANGUAGENAME[u"son"] = u"Songhai languages"
LANGUAGEID_TO_LANGUAGENAME[u"st"] = u"Sotho, Southern"
LANGUAGEID_TO_LANGUAGENAME[u"es"] = u"Spanish; Castilian"
LANGUAGEID_TO_LANGUAGENAME[u"sc"] = u"Sardinian"
LANGUAGEID_TO_LANGUAGENAME[u"srn"] = u"Sranan Tongo"
LANGUAGEID_TO_LANGUAGENAME[u"sr"] = u"Serbian"
LANGUAGEID_TO_LANGUAGENAME[u"srr"] = u"Serer"
LANGUAGEID_TO_LANGUAGENAME[u"ssa"] = u"Nilo-Saharan languages"
LANGUAGEID_TO_LANGUAGENAME[u"ss"] = u"Swati"
LANGUAGEID_TO_LANGUAGENAME[u"suk"] = u"Sukuma"
LANGUAGEID_TO_LANGUAGENAME[u"su"] = u"Sundanese"
LANGUAGEID_TO_LANGUAGENAME[u"sus"] = u"Susu"
LANGUAGEID_TO_LANGUAGENAME[u"sux"] = u"Sumerian"
LANGUAGEID_TO_LANGUAGENAME[u"sw"] = u"Swahili"
LANGUAGEID_TO_LANGUAGENAME[u"sv"] = u"Swedish"
LANGUAGEID_TO_LANGUAGENAME[u"syc"] = u"Classical Syriac"
LANGUAGEID_TO_LANGUAGENAME[u"syr"] = u"Syriac"
LANGUAGEID_TO_LANGUAGENAME[u"ty"] = u"Tahitian"
LANGUAGEID_TO_LANGUAGENAME[u"tai"] = u"Tai languages"
LANGUAGEID_TO_LANGUAGENAME[u"ta"] = u"Tamil"
LANGUAGEID_TO_LANGUAGENAME[u"tt"] = u"Tatar"
LANGUAGEID_TO_LANGUAGENAME[u"te"] = u"Telugu"
LANGUAGEID_TO_LANGUAGENAME[u"tem"] = u"Timne"
LANGUAGEID_TO_LANGUAGENAME[u"ter"] = u"Tereno"
LANGUAGEID_TO_LANGUAGENAME[u"tet"] = u"Tetum"
LANGUAGEID_TO_LANGUAGENAME[u"tg"] = u"Tajik"
LANGUAGEID_TO_LANGUAGENAME[u"tl"] = u"Tagalog"
LANGUAGEID_TO_LANGUAGENAME[u"th"] = u"Thai"
LANGUAGEID_TO_LANGUAGENAME[u"bo"] = u"Tibetan"
LANGUAGEID_TO_LANGUAGENAME[u"tig"] = u"Tigre"
LANGUAGEID_TO_LANGUAGENAME[u"ti"] = u"Tigrinya"
LANGUAGEID_TO_LANGUAGENAME[u"tiv"] = u"Tiv"
LANGUAGEID_TO_LANGUAGENAME[u"tkl"] = u"Tokelau"
LANGUAGEID_TO_LANGUAGENAME[u"tlh"] = u"Klingon; tlhIngan-Hol"
LANGUAGEID_TO_LANGUAGENAME[u"tli"] = u"Tlingit"
LANGUAGEID_TO_LANGUAGENAME[u"tmh"] = u"Tamashek"
LANGUAGEID_TO_LANGUAGENAME[u"tog"] = u"Tonga (Nyasa)"
LANGUAGEID_TO_LANGUAGENAME[u"to"] = u"Tonga (Tonga Islands)"
LANGUAGEID_TO_LANGUAGENAME[u"tpi"] = u"Tok Pisin"
LANGUAGEID_TO_LANGUAGENAME[u"tsi"] = u"Tsimshian"
LANGUAGEID_TO_LANGUAGENAME[u"tn"] = u"Tswana"
LANGUAGEID_TO_LANGUAGENAME[u"ts"] = u"Tsonga"
LANGUAGEID_TO_LANGUAGENAME[u"tk"] = u"Turkmen"
LANGUAGEID_TO_LANGUAGENAME[u"tum"] = u"Tumbuka"
LANGUAGEID_TO_LANGUAGENAME[u"tup"] = u"Tupi languages"
LANGUAGEID_TO_LANGUAGENAME[u"tr"] = u"Turkish"
LANGUAGEID_TO_LANGUAGENAME[u"tut"] = u"Altaic languages"
LANGUAGEID_TO_LANGUAGENAME[u"tvl"] = u"Tuvalu"
LANGUAGEID_TO_LANGUAGENAME[u"tw"] = u"Twi"
LANGUAGEID_TO_LANGUAGENAME[u"tyv"] = u"Tuvinian"
LANGUAGEID_TO_LANGUAGENAME[u"udm"] = u"Udmurt"
LANGUAGEID_TO_LANGUAGENAME[u"uga"] = u"Ugaritic"
LANGUAGEID_TO_LANGUAGENAME[u"ug"] = u"Uighur; Uyghur"
LANGUAGEID_TO_LANGUAGENAME[u"uk"] = u"Ukrainian"
LANGUAGEID_TO_LANGUAGENAME[u"umb"] = u"Umbundu"
LANGUAGEID_TO_LANGUAGENAME[u"und"] = u"Undetermined"
LANGUAGEID_TO_LANGUAGENAME[u"ur"] = u"Urdu"
LANGUAGEID_TO_LANGUAGENAME[u"uz"] = u"Uzbek"
LANGUAGEID_TO_LANGUAGENAME[u"vai"] = u"Vai"
LANGUAGEID_TO_LANGUAGENAME[u"ve"] = u"Venda"
LANGUAGEID_TO_LANGUAGENAME[u"vi"] = u"Vietnamese"
LANGUAGEID_TO_LANGUAGENAME[u"vo"] = u"Volapük"
LANGUAGEID_TO_LANGUAGENAME[u"vot"] = u"Votic"
LANGUAGEID_TO_LANGUAGENAME[u"wak"] = u"Wakashan languages"
LANGUAGEID_TO_LANGUAGENAME[u"wal"] = u"Wolaitta; Wolaytta"
LANGUAGEID_TO_LANGUAGENAME[u"war"] = u"Waray"
LANGUAGEID_TO_LANGUAGENAME[u"was"] = u"Washo"
LANGUAGEID_TO_LANGUAGENAME[u"cy"] = u"Welsh"
LANGUAGEID_TO_LANGUAGENAME[u"wen"] = u"Sorbian languages"
LANGUAGEID_TO_LANGUAGENAME[u"wa"] = u"Walloon"
LANGUAGEID_TO_LANGUAGENAME[u"wo"] = u"Wolof"
LANGUAGEID_TO_LANGUAGENAME[u"xal"] = u"Kalmyk; Oirat"
LANGUAGEID_TO_LANGUAGENAME[u"xh"] = u"Xhosa"
LANGUAGEID_TO_LANGUAGENAME[u"yao"] = u"Yao"
LANGUAGEID_TO_LANGUAGENAME[u"yap"] = u"Yapese"
LANGUAGEID_TO_LANGUAGENAME[u"yi"] = u"Yiddish"
LANGUAGEID_TO_LANGUAGENAME[u"yo"] = u"Yoruba"
LANGUAGEID_TO_LANGUAGENAME[u"ypk"] = u"Yupik languages"
LANGUAGEID_TO_LANGUAGENAME[u"zap"] = u"Zapotec"
LANGUAGEID_TO_LANGUAGENAME[u"zbl"] = u"Blissymbols; Blissymbolics; Bliss"
LANGUAGEID_TO_LANGUAGENAME[u"zen"] = u"Zenaga"
LANGUAGEID_TO_LANGUAGENAME[u"zgh"] = u"Standard Moroccan Tamazight"
LANGUAGEID_TO_LANGUAGENAME[u"za"] = u"Zhuang; Chuang"
LANGUAGEID_TO_LANGUAGENAME[u"znd"] = u"Zande languages"
LANGUAGEID_TO_LANGUAGENAME[u"zu"] = u"Zulu"
LANGUAGEID_TO_LANGUAGENAME[u"zun"] = u"Zuni"
LANGUAGEID_TO_LANGUAGENAME[u"zza"] = u"Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"


LANGUAGENAME_TO_LANGUAGEID = {}
LANGUAGENAME_TO_LANGUAGEID[u"Afar"] = u"aa"
LANGUAGENAME_TO_LANGUAGEID[u"Abkhazian"] = u"ab"
LANGUAGENAME_TO_LANGUAGEID[u"Achinese"] = u"ace"
LANGUAGENAME_TO_LANGUAGEID[u"Acoli"] = u"ach"
LANGUAGENAME_TO_LANGUAGEID[u"Adangme"] = u"ada"
LANGUAGENAME_TO_LANGUAGEID[u"Adyghe; Adygei"] = u"ady"
LANGUAGENAME_TO_LANGUAGEID[u"Afro-Asiatic languages"] = u"afa"
LANGUAGENAME_TO_LANGUAGEID[u"Afrihili"] = u"afh"
LANGUAGENAME_TO_LANGUAGEID[u"Afrikaans"] = u"af"
LANGUAGENAME_TO_LANGUAGEID[u"Ainu"] = u"ain"
LANGUAGENAME_TO_LANGUAGEID[u"Akan"] = u"ak"
LANGUAGENAME_TO_LANGUAGEID[u"Akkadian"] = u"akk"
LANGUAGENAME_TO_LANGUAGEID[u"Albanian"] = u"sq"
LANGUAGENAME_TO_LANGUAGEID[u"Aleut"] = u"ale"
LANGUAGENAME_TO_LANGUAGEID[u"Algonquian languages"] = u"alg"
LANGUAGENAME_TO_LANGUAGEID[u"Southern Altai"] = u"alt"
LANGUAGENAME_TO_LANGUAGEID[u"Amharic"] = u"am"
LANGUAGENAME_TO_LANGUAGEID[u"English, Old (ca. 450-1100)"] = u"ang"
LANGUAGENAME_TO_LANGUAGEID[u"Angika"] = u"anp"
LANGUAGENAME_TO_LANGUAGEID[u"Apache languages"] = u"apa"
LANGUAGENAME_TO_LANGUAGEID[u"Arabic"] = u"ar"
LANGUAGENAME_TO_LANGUAGEID[u"Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)"] = u"arc"
LANGUAGENAME_TO_LANGUAGEID[u"Aragonese"] = u"an"
LANGUAGENAME_TO_LANGUAGEID[u"Armenian"] = u"hy"
LANGUAGENAME_TO_LANGUAGEID[u"Mapudungun; Mapuche"] = u"arn"
LANGUAGENAME_TO_LANGUAGEID[u"Arapaho"] = u"arp"
LANGUAGENAME_TO_LANGUAGEID[u"Artificial languages"] = u"art"
LANGUAGENAME_TO_LANGUAGEID[u"Arawak"] = u"arw"
LANGUAGENAME_TO_LANGUAGEID[u"Assamese"] = u"as"
LANGUAGENAME_TO_LANGUAGEID[u"Asturian; Bable; Leonese; Asturleonese"] = u"ast"
LANGUAGENAME_TO_LANGUAGEID[u"Athapascan languages"] = u"ath"
LANGUAGENAME_TO_LANGUAGEID[u"Australian languages"] = u"aus"
LANGUAGENAME_TO_LANGUAGEID[u"Avaric"] = u"av"
LANGUAGENAME_TO_LANGUAGEID[u"Avestan"] = u"ae"
LANGUAGENAME_TO_LANGUAGEID[u"Awadhi"] = u"awa"
LANGUAGENAME_TO_LANGUAGEID[u"Aymara"] = u"ay"
LANGUAGENAME_TO_LANGUAGEID[u"Azerbaijani"] = u"az"
LANGUAGENAME_TO_LANGUAGEID[u"Banda languages"] = u"bad"
LANGUAGENAME_TO_LANGUAGEID[u"Bamileke languages"] = u"bai"
LANGUAGENAME_TO_LANGUAGEID[u"Bashkir"] = u"ba"
LANGUAGENAME_TO_LANGUAGEID[u"Baluchi"] = u"bal"
LANGUAGENAME_TO_LANGUAGEID[u"Bambara"] = u"bm"
LANGUAGENAME_TO_LANGUAGEID[u"Balinese"] = u"ban"
LANGUAGENAME_TO_LANGUAGEID[u"Basque"] = u"eu"
LANGUAGENAME_TO_LANGUAGEID[u"Basa"] = u"bas"
LANGUAGENAME_TO_LANGUAGEID[u"Baltic languages"] = u"bat"
LANGUAGENAME_TO_LANGUAGEID[u"Beja; Bedawiyet"] = u"bej"
LANGUAGENAME_TO_LANGUAGEID[u"Belarusian"] = u"be"
LANGUAGENAME_TO_LANGUAGEID[u"Bemba"] = u"bem"
LANGUAGENAME_TO_LANGUAGEID[u"Bengali"] = u"bn"
LANGUAGENAME_TO_LANGUAGEID[u"Berber languages"] = u"ber"
LANGUAGENAME_TO_LANGUAGEID[u"Bhojpuri"] = u"bho"
LANGUAGENAME_TO_LANGUAGEID[u"Bihari languages"] = u"bh"
LANGUAGENAME_TO_LANGUAGEID[u"Bikol"] = u"bik"
LANGUAGENAME_TO_LANGUAGEID[u"Bini; Edo"] = u"bin"
LANGUAGENAME_TO_LANGUAGEID[u"Bislama"] = u"bi"
LANGUAGENAME_TO_LANGUAGEID[u"Siksika"] = u"bla"
LANGUAGENAME_TO_LANGUAGEID[u"Bantu languages"] = u"bnt"
LANGUAGENAME_TO_LANGUAGEID[u"Bosnian"] = u"bs"
LANGUAGENAME_TO_LANGUAGEID[u"Braj"] = u"bra"
LANGUAGENAME_TO_LANGUAGEID[u"Breton"] = u"br"
LANGUAGENAME_TO_LANGUAGEID[u"Batak languages"] = u"btk"
LANGUAGENAME_TO_LANGUAGEID[u"Buriat"] = u"bua"
LANGUAGENAME_TO_LANGUAGEID[u"Buginese"] = u"bug"
LANGUAGENAME_TO_LANGUAGEID[u"Bulgarian"] = u"bg"
LANGUAGENAME_TO_LANGUAGEID[u"Burmese"] = u"my"
LANGUAGENAME_TO_LANGUAGEID[u"Blin; Bilin"] = u"byn"
LANGUAGENAME_TO_LANGUAGEID[u"Caddo"] = u"cad"
LANGUAGENAME_TO_LANGUAGEID[u"Central American Indian languages"] = u"cai"
LANGUAGENAME_TO_LANGUAGEID[u"Galibi Carib"] = u"car"
LANGUAGENAME_TO_LANGUAGEID[u"Catalan; Valencian"] = u"ca"
LANGUAGENAME_TO_LANGUAGEID[u"Caucasian languages"] = u"cau"
LANGUAGENAME_TO_LANGUAGEID[u"Cebuano"] = u"ceb"
LANGUAGENAME_TO_LANGUAGEID[u"Celtic languages"] = u"cel"
LANGUAGENAME_TO_LANGUAGEID[u"Chamorro"] = u"ch"
LANGUAGENAME_TO_LANGUAGEID[u"Chibcha"] = u"chb"
LANGUAGENAME_TO_LANGUAGEID[u"Chechen"] = u"ce"
LANGUAGENAME_TO_LANGUAGEID[u"Chagatai"] = u"chg"
LANGUAGENAME_TO_LANGUAGEID[u"Chinese"] = u"zh"
LANGUAGENAME_TO_LANGUAGEID[u"Chuukese"] = u"chk"
LANGUAGENAME_TO_LANGUAGEID[u"Mari"] = u"chm"
LANGUAGENAME_TO_LANGUAGEID[u"Chinook jargon"] = u"chn"
LANGUAGENAME_TO_LANGUAGEID[u"Choctaw"] = u"cho"
LANGUAGENAME_TO_LANGUAGEID[u"Chipewyan; Dene Suline"] = u"chp"
LANGUAGENAME_TO_LANGUAGEID[u"Cherokee"] = u"chr"
LANGUAGENAME_TO_LANGUAGEID[u"Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"] = u"cu"
LANGUAGENAME_TO_LANGUAGEID[u"Chuvash"] = u"cv"
LANGUAGENAME_TO_LANGUAGEID[u"Cheyenne"] = u"chy"
LANGUAGENAME_TO_LANGUAGEID[u"Chamic languages"] = u"cmc"
LANGUAGENAME_TO_LANGUAGEID[u"Coptic"] = u"cop"
LANGUAGENAME_TO_LANGUAGEID[u"Cornish"] = u"kw"
LANGUAGENAME_TO_LANGUAGEID[u"Corsican"] = u"co"
LANGUAGENAME_TO_LANGUAGEID[u"Creoles and pidgins, English based"] = u"cpe"
LANGUAGENAME_TO_LANGUAGEID[u"Creoles and pidgins, French-based"] = u"cpf"
LANGUAGENAME_TO_LANGUAGEID[u"Creoles and pidgins, Portuguese-based"] = u"cpp"
LANGUAGENAME_TO_LANGUAGEID[u"Cree"] = u"cr"
LANGUAGENAME_TO_LANGUAGEID[u"Crimean Tatar; Crimean Turkish"] = u"crh"
LANGUAGENAME_TO_LANGUAGEID[u"Creoles and pidgins"] = u"crp"
LANGUAGENAME_TO_LANGUAGEID[u"Kashubian"] = u"csb"
LANGUAGENAME_TO_LANGUAGEID[u"Cushitic languages"] = u"cus"
LANGUAGENAME_TO_LANGUAGEID[u"Czech"] = u"cs"
LANGUAGENAME_TO_LANGUAGEID[u"Dakota"] = u"dak"
LANGUAGENAME_TO_LANGUAGEID[u"Danish"] = u"da"
LANGUAGENAME_TO_LANGUAGEID[u"Dargwa"] = u"dar"
LANGUAGENAME_TO_LANGUAGEID[u"Land Dayak languages"] = u"day"
LANGUAGENAME_TO_LANGUAGEID[u"Delaware"] = u"del"
LANGUAGENAME_TO_LANGUAGEID[u"Slave (Athapascan)"] = u"den"
LANGUAGENAME_TO_LANGUAGEID[u"Dogrib"] = u"dgr"
LANGUAGENAME_TO_LANGUAGEID[u"Dinka"] = u"din"
LANGUAGENAME_TO_LANGUAGEID[u"Divehi; Dhivehi; Maldivian"] = u"dv"
LANGUAGENAME_TO_LANGUAGEID[u"Dogri"] = u"doi"
LANGUAGENAME_TO_LANGUAGEID[u"Dravidian languages"] = u"dra"
LANGUAGENAME_TO_LANGUAGEID[u"Lower Sorbian"] = u"dsb"
LANGUAGENAME_TO_LANGUAGEID[u"Duala"] = u"dua"
LANGUAGENAME_TO_LANGUAGEID[u"Dutch, Middle (ca. 1050-1350)"] = u"dum"
LANGUAGENAME_TO_LANGUAGEID[u"Dutch; Flemish"] = u"nl"
LANGUAGENAME_TO_LANGUAGEID[u"Dyula"] = u"dyu"
LANGUAGENAME_TO_LANGUAGEID[u"Dzongkha"] = u"dz"
LANGUAGENAME_TO_LANGUAGEID[u"Efik"] = u"efi"
LANGUAGENAME_TO_LANGUAGEID[u"Egyptian (Ancient)"] = u"egy"
LANGUAGENAME_TO_LANGUAGEID[u"Ekajuk"] = u"eka"
LANGUAGENAME_TO_LANGUAGEID[u"Elamite"] = u"elx"
LANGUAGENAME_TO_LANGUAGEID[u"English"] = u"en"
LANGUAGENAME_TO_LANGUAGEID[u"English, Middle (1100-1500)"] = u"enm"
LANGUAGENAME_TO_LANGUAGEID[u"Esperanto"] = u"eo"
LANGUAGENAME_TO_LANGUAGEID[u"Estonian"] = u"et"
LANGUAGENAME_TO_LANGUAGEID[u"Ewe"] = u"ee"
LANGUAGENAME_TO_LANGUAGEID[u"Ewondo"] = u"ewo"
LANGUAGENAME_TO_LANGUAGEID[u"Fang"] = u"fan"
LANGUAGENAME_TO_LANGUAGEID[u"Faroese"] = u"fo"
LANGUAGENAME_TO_LANGUAGEID[u"Fanti"] = u"fat"
LANGUAGENAME_TO_LANGUAGEID[u"Fijian"] = u"fj"
LANGUAGENAME_TO_LANGUAGEID[u"Filipino; Pilipino"] = u"fil"
LANGUAGENAME_TO_LANGUAGEID[u"Finnish"] = u"fi"
LANGUAGENAME_TO_LANGUAGEID[u"Finno-Ugrian languages"] = u"fiu"
LANGUAGENAME_TO_LANGUAGEID[u"Fon"] = u"fon"
LANGUAGENAME_TO_LANGUAGEID[u"French"] = u"fr"
LANGUAGENAME_TO_LANGUAGEID[u"French, Middle (ca. 1400-1600)"] = u"frm"
LANGUAGENAME_TO_LANGUAGEID[u"French, Old (842-ca. 1400)"] = u"fro"
LANGUAGENAME_TO_LANGUAGEID[u"Northern Frisian"] = u"frr"
LANGUAGENAME_TO_LANGUAGEID[u"Eastern Frisian"] = u"frs"
LANGUAGENAME_TO_LANGUAGEID[u"Western Frisian"] = u"fy"
LANGUAGENAME_TO_LANGUAGEID[u"Fulah"] = u"ff"
LANGUAGENAME_TO_LANGUAGEID[u"Friulian"] = u"fur"
LANGUAGENAME_TO_LANGUAGEID[u"Ga"] = u"gaa"
LANGUAGENAME_TO_LANGUAGEID[u"Gayo"] = u"gay"
LANGUAGENAME_TO_LANGUAGEID[u"Gbaya"] = u"gba"
LANGUAGENAME_TO_LANGUAGEID[u"Germanic languages"] = u"gem"
LANGUAGENAME_TO_LANGUAGEID[u"Georgian"] = u"ka"
LANGUAGENAME_TO_LANGUAGEID[u"German"] = u"de"
LANGUAGENAME_TO_LANGUAGEID[u"Geez"] = u"gez"
LANGUAGENAME_TO_LANGUAGEID[u"Gilbertese"] = u"gil"
LANGUAGENAME_TO_LANGUAGEID[u"Gaelic; Scottish Gaelic"] = u"gd"
LANGUAGENAME_TO_LANGUAGEID[u"Irish"] = u"ga"
LANGUAGENAME_TO_LANGUAGEID[u"Galician"] = u"gl"
LANGUAGENAME_TO_LANGUAGEID[u"Manx"] = u"gv"
LANGUAGENAME_TO_LANGUAGEID[u"German, Middle High (ca. 1050-1500)"] = u"gmh"
LANGUAGENAME_TO_LANGUAGEID[u"German, Old High (ca. 750-1050)"] = u"goh"
LANGUAGENAME_TO_LANGUAGEID[u"Gondi"] = u"gon"
LANGUAGENAME_TO_LANGUAGEID[u"Gorontalo"] = u"gor"
LANGUAGENAME_TO_LANGUAGEID[u"Gothic"] = u"got"
LANGUAGENAME_TO_LANGUAGEID[u"Grebo"] = u"grb"
LANGUAGENAME_TO_LANGUAGEID[u"Greek, Ancient (to 1453)"] = u"grc"
LANGUAGENAME_TO_LANGUAGEID[u"Greek, Modern (1453-)"] = u"el"
LANGUAGENAME_TO_LANGUAGEID[u"Guarani"] = u"gn"
LANGUAGENAME_TO_LANGUAGEID[u"Swiss German; Alemannic; Alsatian"] = u"gsw"
LANGUAGENAME_TO_LANGUAGEID[u"Gujarati"] = u"gu"
LANGUAGENAME_TO_LANGUAGEID[u"Gwich'in"] = u"gwi"
LANGUAGENAME_TO_LANGUAGEID[u"Haida"] = u"hai"
LANGUAGENAME_TO_LANGUAGEID[u"Haitian; Haitian Creole"] = u"ht"
LANGUAGENAME_TO_LANGUAGEID[u"Hausa"] = u"ha"
LANGUAGENAME_TO_LANGUAGEID[u"Hawaiian"] = u"haw"
LANGUAGENAME_TO_LANGUAGEID[u"Hebrew"] = u"he"
LANGUAGENAME_TO_LANGUAGEID[u"Herero"] = u"hz"
LANGUAGENAME_TO_LANGUAGEID[u"Hiligaynon"] = u"hil"
LANGUAGENAME_TO_LANGUAGEID[u"Himachali languages; Western Pahari languages"] = u"him"
LANGUAGENAME_TO_LANGUAGEID[u"Hindi"] = u"hi"
LANGUAGENAME_TO_LANGUAGEID[u"Hittite"] = u"hit"
LANGUAGENAME_TO_LANGUAGEID[u"Hmong; Mong"] = u"hmn"
LANGUAGENAME_TO_LANGUAGEID[u"Hiri Motu"] = u"ho"
LANGUAGENAME_TO_LANGUAGEID[u"Croatian"] = u"hr"
LANGUAGENAME_TO_LANGUAGEID[u"Upper Sorbian"] = u"hsb"
LANGUAGENAME_TO_LANGUAGEID[u"Hungarian"] = u"hu"
LANGUAGENAME_TO_LANGUAGEID[u"Hupa"] = u"hup"
LANGUAGENAME_TO_LANGUAGEID[u"Iban"] = u"iba"
LANGUAGENAME_TO_LANGUAGEID[u"Igbo"] = u"ig"
LANGUAGENAME_TO_LANGUAGEID[u"Icelandic"] = u"is"
LANGUAGENAME_TO_LANGUAGEID[u"Ido"] = u"io"
LANGUAGENAME_TO_LANGUAGEID[u"Sichuan Yi; Nuosu"] = u"ii"
LANGUAGENAME_TO_LANGUAGEID[u"Ijo languages"] = u"ijo"
LANGUAGENAME_TO_LANGUAGEID[u"Inuktitut"] = u"iu"
LANGUAGENAME_TO_LANGUAGEID[u"Interlingue; Occidental"] = u"ie"
LANGUAGENAME_TO_LANGUAGEID[u"Iloko"] = u"ilo"
LANGUAGENAME_TO_LANGUAGEID[u"Interlingua (International Auxiliary Language Association)"] = u"ia"
LANGUAGENAME_TO_LANGUAGEID[u"Indic languages"] = u"inc"
LANGUAGENAME_TO_LANGUAGEID[u"Indonesian"] = u"id"
LANGUAGENAME_TO_LANGUAGEID[u"Indo-European languages"] = u"ine"
LANGUAGENAME_TO_LANGUAGEID[u"Ingush"] = u"inh"
LANGUAGENAME_TO_LANGUAGEID[u"Inupiaq"] = u"ik"
LANGUAGENAME_TO_LANGUAGEID[u"Iranian languages"] = u"ira"
LANGUAGENAME_TO_LANGUAGEID[u"Iroquoian languages"] = u"iro"
LANGUAGENAME_TO_LANGUAGEID[u"Italian"] = u"it"
LANGUAGENAME_TO_LANGUAGEID[u"Javanese"] = u"jv"
LANGUAGENAME_TO_LANGUAGEID[u"Lojban"] = u"jbo"
LANGUAGENAME_TO_LANGUAGEID[u"Japanese"] = u"ja"
LANGUAGENAME_TO_LANGUAGEID[u"Judeo-Persian"] = u"jpr"
LANGUAGENAME_TO_LANGUAGEID[u"Judeo-Arabic"] = u"jrb"
LANGUAGENAME_TO_LANGUAGEID[u"Kara-Kalpak"] = u"kaa"
LANGUAGENAME_TO_LANGUAGEID[u"Kabyle"] = u"kab"
LANGUAGENAME_TO_LANGUAGEID[u"Kachin; Jingpho"] = u"kac"
LANGUAGENAME_TO_LANGUAGEID[u"Kalaallisut; Greenlandic"] = u"kl"
LANGUAGENAME_TO_LANGUAGEID[u"Kamba"] = u"kam"
LANGUAGENAME_TO_LANGUAGEID[u"Kannada"] = u"kn"
LANGUAGENAME_TO_LANGUAGEID[u"Karen languages"] = u"kar"
LANGUAGENAME_TO_LANGUAGEID[u"Kashmiri"] = u"ks"
LANGUAGENAME_TO_LANGUAGEID[u"Kanuri"] = u"kr"
LANGUAGENAME_TO_LANGUAGEID[u"Kawi"] = u"kaw"
LANGUAGENAME_TO_LANGUAGEID[u"Kazakh"] = u"kk"
LANGUAGENAME_TO_LANGUAGEID[u"Kabardian"] = u"kbd"
LANGUAGENAME_TO_LANGUAGEID[u"Khasi"] = u"kha"
LANGUAGENAME_TO_LANGUAGEID[u"Khoisan languages"] = u"khi"
LANGUAGENAME_TO_LANGUAGEID[u"Central Khmer"] = u"km"
LANGUAGENAME_TO_LANGUAGEID[u"Khotanese;Sakan"] = u"kho"
LANGUAGENAME_TO_LANGUAGEID[u"Kikuyu; Gikuyu"] = u"ki"
LANGUAGENAME_TO_LANGUAGEID[u"Kinyarwanda"] = u"rw"
LANGUAGENAME_TO_LANGUAGEID[u"Kirghiz; Kyrgyz"] = u"ky"
LANGUAGENAME_TO_LANGUAGEID[u"Kimbundu"] = u"kmb"
LANGUAGENAME_TO_LANGUAGEID[u"Konkani"] = u"kok"
LANGUAGENAME_TO_LANGUAGEID[u"Komi"] = u"kv"
LANGUAGENAME_TO_LANGUAGEID[u"Kongo"] = u"kg"
LANGUAGENAME_TO_LANGUAGEID[u"Korean"] = u"ko"
LANGUAGENAME_TO_LANGUAGEID[u"Kosraean"] = u"kos"
LANGUAGENAME_TO_LANGUAGEID[u"Kpelle"] = u"kpe"
LANGUAGENAME_TO_LANGUAGEID[u"Karachay-Balkar"] = u"krc"
LANGUAGENAME_TO_LANGUAGEID[u"Karelian"] = u"krl"
LANGUAGENAME_TO_LANGUAGEID[u"Kru languages"] = u"kro"
LANGUAGENAME_TO_LANGUAGEID[u"Kurukh"] = u"kru"
LANGUAGENAME_TO_LANGUAGEID[u"Kuanyama; Kwanyama"] = u"kj"
LANGUAGENAME_TO_LANGUAGEID[u"Kumyk"] = u"kum"
LANGUAGENAME_TO_LANGUAGEID[u"Kurdish"] = u"ku"
LANGUAGENAME_TO_LANGUAGEID[u"Kutenai"] = u"kut"
LANGUAGENAME_TO_LANGUAGEID[u"Ladino"] = u"lad"
LANGUAGENAME_TO_LANGUAGEID[u"Lahnda"] = u"lah"
LANGUAGENAME_TO_LANGUAGEID[u"Lamba"] = u"lam"
LANGUAGENAME_TO_LANGUAGEID[u"Lao"] = u"lo"
LANGUAGENAME_TO_LANGUAGEID[u"Latin"] = u"la"
LANGUAGENAME_TO_LANGUAGEID[u"Latvian"] = u"lv"
LANGUAGENAME_TO_LANGUAGEID[u"Lezghian"] = u"lez"
LANGUAGENAME_TO_LANGUAGEID[u"Limburgan; Limburger; Limburgish"] = u"li"
LANGUAGENAME_TO_LANGUAGEID[u"Lingala"] = u"ln"
LANGUAGENAME_TO_LANGUAGEID[u"Lithuanian"] = u"lt"
LANGUAGENAME_TO_LANGUAGEID[u"Mongo"] = u"lol"
LANGUAGENAME_TO_LANGUAGEID[u"Lozi"] = u"loz"
LANGUAGENAME_TO_LANGUAGEID[u"Luxembourgish; Letzeburgesch"] = u"lb"
LANGUAGENAME_TO_LANGUAGEID[u"Luba-Lulua"] = u"lua"
LANGUAGENAME_TO_LANGUAGEID[u"Luba-Katanga"] = u"lu"
LANGUAGENAME_TO_LANGUAGEID[u"Ganda"] = u"lg"
LANGUAGENAME_TO_LANGUAGEID[u"Luiseno"] = u"lui"
LANGUAGENAME_TO_LANGUAGEID[u"Lunda"] = u"lun"
LANGUAGENAME_TO_LANGUAGEID[u"Luo (Kenya and Tanzania)"] = u"luo"
LANGUAGENAME_TO_LANGUAGEID[u"Lushai"] = u"lus"
LANGUAGENAME_TO_LANGUAGEID[u"Macedonian"] = u"mk"
LANGUAGENAME_TO_LANGUAGEID[u"Madurese"] = u"mad"
LANGUAGENAME_TO_LANGUAGEID[u"Magahi"] = u"mag"
LANGUAGENAME_TO_LANGUAGEID[u"Marshallese"] = u"mh"
LANGUAGENAME_TO_LANGUAGEID[u"Maithili"] = u"mai"
LANGUAGENAME_TO_LANGUAGEID[u"Makasar"] = u"mak"
LANGUAGENAME_TO_LANGUAGEID[u"Malayalam"] = u"ml"
LANGUAGENAME_TO_LANGUAGEID[u"Mandingo"] = u"man"
LANGUAGENAME_TO_LANGUAGEID[u"Maori"] = u"mi"
LANGUAGENAME_TO_LANGUAGEID[u"Austronesian languages"] = u"map"
LANGUAGENAME_TO_LANGUAGEID[u"Marathi"] = u"mr"
LANGUAGENAME_TO_LANGUAGEID[u"Masai"] = u"mas"
LANGUAGENAME_TO_LANGUAGEID[u"Malay"] = u"ms"
LANGUAGENAME_TO_LANGUAGEID[u"Moksha"] = u"mdf"
LANGUAGENAME_TO_LANGUAGEID[u"Mandar"] = u"mdr"
LANGUAGENAME_TO_LANGUAGEID[u"Mende"] = u"men"
LANGUAGENAME_TO_LANGUAGEID[u"Irish, Middle (900-1200)"] = u"mga"
LANGUAGENAME_TO_LANGUAGEID[u"Mi'kmaq; Micmac"] = u"mic"
LANGUAGENAME_TO_LANGUAGEID[u"Minangkabau"] = u"min"
LANGUAGENAME_TO_LANGUAGEID[u"Uncoded languages"] = u"mis"
LANGUAGENAME_TO_LANGUAGEID[u"Mon-Khmer languages"] = u"mkh"
LANGUAGENAME_TO_LANGUAGEID[u"Malagasy"] = u"mg"
LANGUAGENAME_TO_LANGUAGEID[u"Maltese"] = u"mt"
LANGUAGENAME_TO_LANGUAGEID[u"Manchu"] = u"mnc"
LANGUAGENAME_TO_LANGUAGEID[u"Manipuri"] = u"mni"
LANGUAGENAME_TO_LANGUAGEID[u"Manobo languages"] = u"mno"
LANGUAGENAME_TO_LANGUAGEID[u"Mohawk"] = u"moh"
LANGUAGENAME_TO_LANGUAGEID[u"Moldavian; Moldovan"] = u"mo"
LANGUAGENAME_TO_LANGUAGEID[u"Mongolian"] = u"mn"
LANGUAGENAME_TO_LANGUAGEID[u"Mossi"] = u"mos"
LANGUAGENAME_TO_LANGUAGEID[u"Multiple languages"] = u"mul"
LANGUAGENAME_TO_LANGUAGEID[u"Munda languages"] = u"mun"
LANGUAGENAME_TO_LANGUAGEID[u"Creek"] = u"mus"
LANGUAGENAME_TO_LANGUAGEID[u"Mirandese"] = u"mwl"
LANGUAGENAME_TO_LANGUAGEID[u"Marwari"] = u"mwr"
LANGUAGENAME_TO_LANGUAGEID[u"Mayan languages"] = u"myn"
LANGUAGENAME_TO_LANGUAGEID[u"Erzya"] = u"myv"
LANGUAGENAME_TO_LANGUAGEID[u"Nahuatl languages"] = u"nah"
LANGUAGENAME_TO_LANGUAGEID[u"North American Indian languages"] = u"nai"
LANGUAGENAME_TO_LANGUAGEID[u"Neapolitan"] = u"nap"
LANGUAGENAME_TO_LANGUAGEID[u"Nauru"] = u"na"
LANGUAGENAME_TO_LANGUAGEID[u"Navajo; Navaho"] = u"nv"
LANGUAGENAME_TO_LANGUAGEID[u"Ndebele, South; South Ndebele"] = u"nr"
LANGUAGENAME_TO_LANGUAGEID[u"Ndebele, North; North Ndebele"] = u"nd"
LANGUAGENAME_TO_LANGUAGEID[u"Ndonga"] = u"ng"
LANGUAGENAME_TO_LANGUAGEID[u"Low German; Low Saxon; German, Low; Saxon, Low"] = u"nds"
LANGUAGENAME_TO_LANGUAGEID[u"Nepali"] = u"ne"
LANGUAGENAME_TO_LANGUAGEID[u"Nepal Bhasa; Newari"] = u"new"
LANGUAGENAME_TO_LANGUAGEID[u"Nias"] = u"nia"
LANGUAGENAME_TO_LANGUAGEID[u"Niger-Kordofanian languages"] = u"nic"
LANGUAGENAME_TO_LANGUAGEID[u"Niuean"] = u"niu"
LANGUAGENAME_TO_LANGUAGEID[u"Norwegian Nynorsk; Nynorsk, Norwegian"] = u"nn"
LANGUAGENAME_TO_LANGUAGEID[u"Bokmål, Norwegian; Norwegian Bokmål"] = u"nb"
LANGUAGENAME_TO_LANGUAGEID[u"Nogai"] = u"nog"
LANGUAGENAME_TO_LANGUAGEID[u"Norse, Old"] = u"non"
LANGUAGENAME_TO_LANGUAGEID[u"Norwegian"] = u"no"
LANGUAGENAME_TO_LANGUAGEID[u"N'Ko"] = u"nqo"
LANGUAGENAME_TO_LANGUAGEID[u"Pedi; Sepedi; Northern Sotho"] = u"nso"
LANGUAGENAME_TO_LANGUAGEID[u"Nubian languages"] = u"nub"
LANGUAGENAME_TO_LANGUAGEID[u"Classical Newari; Old Newari; Classical Nepal Bhasa"] = u"nwc"
LANGUAGENAME_TO_LANGUAGEID[u"Chichewa; Chewa; Nyanja"] = u"ny"
LANGUAGENAME_TO_LANGUAGEID[u"Nyamwezi"] = u"nym"
LANGUAGENAME_TO_LANGUAGEID[u"Nyankole"] = u"nyn"
LANGUAGENAME_TO_LANGUAGEID[u"Nyoro"] = u"nyo"
LANGUAGENAME_TO_LANGUAGEID[u"Nzima"] = u"nzi"
LANGUAGENAME_TO_LANGUAGEID[u"Occitan (post 1500)"] = u"oc"
LANGUAGENAME_TO_LANGUAGEID[u"Ojibwa"] = u"oj"
LANGUAGENAME_TO_LANGUAGEID[u"Oriya"] = u"or"
LANGUAGENAME_TO_LANGUAGEID[u"Oromo"] = u"om"
LANGUAGENAME_TO_LANGUAGEID[u"Osage"] = u"osa"
LANGUAGENAME_TO_LANGUAGEID[u"Ossetian; Ossetic"] = u"os"
LANGUAGENAME_TO_LANGUAGEID[u"Turkish, Ottoman (1500-1928)"] = u"ota"
LANGUAGENAME_TO_LANGUAGEID[u"Otomian languages"] = u"oto"
LANGUAGENAME_TO_LANGUAGEID[u"Papuan languages"] = u"paa"
LANGUAGENAME_TO_LANGUAGEID[u"Pangasinan"] = u"pag"
LANGUAGENAME_TO_LANGUAGEID[u"Pahlavi"] = u"pal"
LANGUAGENAME_TO_LANGUAGEID[u"Pampanga; Kapampangan"] = u"pam"
LANGUAGENAME_TO_LANGUAGEID[u"Panjabi; Punjabi"] = u"pa"
LANGUAGENAME_TO_LANGUAGEID[u"Papiamento"] = u"pap"
LANGUAGENAME_TO_LANGUAGEID[u"Palauan"] = u"pau"
LANGUAGENAME_TO_LANGUAGEID[u"Persian, Old (ca. 600-400 B.C.)"] = u"peo"
LANGUAGENAME_TO_LANGUAGEID[u"Persian"] = u"fa"
LANGUAGENAME_TO_LANGUAGEID[u"Philippine languages"] = u"phi"
LANGUAGENAME_TO_LANGUAGEID[u"Phoenician"] = u"phn"
LANGUAGENAME_TO_LANGUAGEID[u"Pali"] = u"pi"
LANGUAGENAME_TO_LANGUAGEID[u"Polish"] = u"pl"
LANGUAGENAME_TO_LANGUAGEID[u"Pohnpeian"] = u"pon"
LANGUAGENAME_TO_LANGUAGEID[u"Portuguese"] = u"pt"
LANGUAGENAME_TO_LANGUAGEID[u"Prakrit languages"] = u"pra"
LANGUAGENAME_TO_LANGUAGEID[u"Provençal, Old (to 1500); Occitan, Old (to 1500)"] = u"pro"
LANGUAGENAME_TO_LANGUAGEID[u"Pushto; Pashto"] = u"ps"
LANGUAGENAME_TO_LANGUAGEID[u"Quechua"] = u"qu"
LANGUAGENAME_TO_LANGUAGEID[u"Rajasthani"] = u"raj"
LANGUAGENAME_TO_LANGUAGEID[u"Rapanui"] = u"rap"
LANGUAGENAME_TO_LANGUAGEID[u"Rarotongan; Cook Islands Maori"] = u"rar"
LANGUAGENAME_TO_LANGUAGEID[u"Romance languages"] = u"roa"
LANGUAGENAME_TO_LANGUAGEID[u"Romansh"] = u"rm"
LANGUAGENAME_TO_LANGUAGEID[u"Romany"] = u"rom"
LANGUAGENAME_TO_LANGUAGEID[u"Romanian"] = u"ro"
LANGUAGENAME_TO_LANGUAGEID[u"Rundi"] = u"rn"
LANGUAGENAME_TO_LANGUAGEID[u"Aromanian; Arumanian; Macedo-Romanian"] = u"rup"
LANGUAGENAME_TO_LANGUAGEID[u"Russian"] = u"ru"
LANGUAGENAME_TO_LANGUAGEID[u"Sandawe"] = u"sad"
LANGUAGENAME_TO_LANGUAGEID[u"Sango"] = u"sg"
LANGUAGENAME_TO_LANGUAGEID[u"Yakut"] = u"sah"
LANGUAGENAME_TO_LANGUAGEID[u"South American Indian languages"] = u"sai"
LANGUAGENAME_TO_LANGUAGEID[u"Salishan languages"] = u"sal"
LANGUAGENAME_TO_LANGUAGEID[u"Samaritan Aramaic"] = u"sam"
LANGUAGENAME_TO_LANGUAGEID[u"Sanskrit"] = u"sa"
LANGUAGENAME_TO_LANGUAGEID[u"Sasak"] = u"sas"
LANGUAGENAME_TO_LANGUAGEID[u"Santali"] = u"sat"
LANGUAGENAME_TO_LANGUAGEID[u"Sicilian"] = u"scn"
LANGUAGENAME_TO_LANGUAGEID[u"Scots"] = u"sco"
LANGUAGENAME_TO_LANGUAGEID[u"Selkup"] = u"sel"
LANGUAGENAME_TO_LANGUAGEID[u"Semitic languages"] = u"sem"
LANGUAGENAME_TO_LANGUAGEID[u"Irish, Old (to 900)"] = u"sga"
LANGUAGENAME_TO_LANGUAGEID[u"Sign Languages"] = u"sgn"
LANGUAGENAME_TO_LANGUAGEID[u"Shan"] = u"shn"
LANGUAGENAME_TO_LANGUAGEID[u"Sidamo"] = u"sid"
LANGUAGENAME_TO_LANGUAGEID[u"Sinhala; Sinhalese"] = u"si"
LANGUAGENAME_TO_LANGUAGEID[u"Siouan languages"] = u"sio"
LANGUAGENAME_TO_LANGUAGEID[u"Sino-Tibetan languages"] = u"sit"
LANGUAGENAME_TO_LANGUAGEID[u"Slavic languages"] = u"sla"
LANGUAGENAME_TO_LANGUAGEID[u"Slovak"] = u"sk"
LANGUAGENAME_TO_LANGUAGEID[u"Slovenian"] = u"sl"
LANGUAGENAME_TO_LANGUAGEID[u"Southern Sami"] = u"sma"
LANGUAGENAME_TO_LANGUAGEID[u"Northern Sami"] = u"se"
LANGUAGENAME_TO_LANGUAGEID[u"Sami languages"] = u"smi"
LANGUAGENAME_TO_LANGUAGEID[u"Lule Sami"] = u"smj"
LANGUAGENAME_TO_LANGUAGEID[u"Inari Sami"] = u"smn"
LANGUAGENAME_TO_LANGUAGEID[u"Samoan"] = u"sm"
LANGUAGENAME_TO_LANGUAGEID[u"Skolt Sami"] = u"sms"
LANGUAGENAME_TO_LANGUAGEID[u"Shona"] = u"sn"
LANGUAGENAME_TO_LANGUAGEID[u"Sindhi"] = u"sd"
LANGUAGENAME_TO_LANGUAGEID[u"Soninke"] = u"snk"
LANGUAGENAME_TO_LANGUAGEID[u"Sogdian"] = u"sog"
LANGUAGENAME_TO_LANGUAGEID[u"Somali"] = u"so"
LANGUAGENAME_TO_LANGUAGEID[u"Songhai languages"] = u"son"
LANGUAGENAME_TO_LANGUAGEID[u"Sotho, Southern"] = u"st"
LANGUAGENAME_TO_LANGUAGEID[u"Spanish; Castilian"] = u"es"
LANGUAGENAME_TO_LANGUAGEID[u"Sardinian"] = u"sc"
LANGUAGENAME_TO_LANGUAGEID[u"Sranan Tongo"] = u"srn"
LANGUAGENAME_TO_LANGUAGEID[u"Serbian"] = u"sr"
LANGUAGENAME_TO_LANGUAGEID[u"Serer"] = u"srr"
LANGUAGENAME_TO_LANGUAGEID[u"Nilo-Saharan languages"] = u"ssa"
LANGUAGENAME_TO_LANGUAGEID[u"Swati"] = u"ss"
LANGUAGENAME_TO_LANGUAGEID[u"Sukuma"] = u"suk"
LANGUAGENAME_TO_LANGUAGEID[u"Sundanese"] = u"su"
LANGUAGENAME_TO_LANGUAGEID[u"Susu"] = u"sus"
LANGUAGENAME_TO_LANGUAGEID[u"Sumerian"] = u"sux"
LANGUAGENAME_TO_LANGUAGEID[u"Swahili"] = u"sw"
LANGUAGENAME_TO_LANGUAGEID[u"Swedish"] = u"sv"
LANGUAGENAME_TO_LANGUAGEID[u"Classical Syriac"] = u"syc"
LANGUAGENAME_TO_LANGUAGEID[u"Syriac"] = u"syr"
LANGUAGENAME_TO_LANGUAGEID[u"Tahitian"] = u"ty"
LANGUAGENAME_TO_LANGUAGEID[u"Tai languages"] = u"tai"
LANGUAGENAME_TO_LANGUAGEID[u"Tamil"] = u"ta"
LANGUAGENAME_TO_LANGUAGEID[u"Tatar"] = u"tt"
LANGUAGENAME_TO_LANGUAGEID[u"Telugu"] = u"te"
LANGUAGENAME_TO_LANGUAGEID[u"Timne"] = u"tem"
LANGUAGENAME_TO_LANGUAGEID[u"Tereno"] = u"ter"
LANGUAGENAME_TO_LANGUAGEID[u"Tetum"] = u"tet"
LANGUAGENAME_TO_LANGUAGEID[u"Tajik"] = u"tg"
LANGUAGENAME_TO_LANGUAGEID[u"Tagalog"] = u"tl"
LANGUAGENAME_TO_LANGUAGEID[u"Thai"] = u"th"
LANGUAGENAME_TO_LANGUAGEID[u"Tibetan"] = u"bo"
LANGUAGENAME_TO_LANGUAGEID[u"Tigre"] = u"tig"
LANGUAGENAME_TO_LANGUAGEID[u"Tigrinya"] = u"ti"
LANGUAGENAME_TO_LANGUAGEID[u"Tiv"] = u"tiv"
LANGUAGENAME_TO_LANGUAGEID[u"Tokelau"] = u"tkl"
LANGUAGENAME_TO_LANGUAGEID[u"Klingon; tlhIngan-Hol"] = u"tlh"
LANGUAGENAME_TO_LANGUAGEID[u"Tlingit"] = u"tli"
LANGUAGENAME_TO_LANGUAGEID[u"Tamashek"] = u"tmh"
LANGUAGENAME_TO_LANGUAGEID[u"Tonga (Nyasa)"] = u"tog"
LANGUAGENAME_TO_LANGUAGEID[u"Tonga (Tonga Islands)"] = u"to"
LANGUAGENAME_TO_LANGUAGEID[u"Tok Pisin"] = u"tpi"
LANGUAGENAME_TO_LANGUAGEID[u"Tsimshian"] = u"tsi"
LANGUAGENAME_TO_LANGUAGEID[u"Tswana"] = u"tn"
LANGUAGENAME_TO_LANGUAGEID[u"Tsonga"] = u"ts"
LANGUAGENAME_TO_LANGUAGEID[u"Turkmen"] = u"tk"
LANGUAGENAME_TO_LANGUAGEID[u"Tumbuka"] = u"tum"
LANGUAGENAME_TO_LANGUAGEID[u"Tupi languages"] = u"tup"
LANGUAGENAME_TO_LANGUAGEID[u"Turkish"] = u"tr"
LANGUAGENAME_TO_LANGUAGEID[u"Altaic languages"] = u"tut"
LANGUAGENAME_TO_LANGUAGEID[u"Tuvalu"] = u"tvl"
LANGUAGENAME_TO_LANGUAGEID[u"Twi"] = u"tw"
LANGUAGENAME_TO_LANGUAGEID[u"Tuvinian"] = u"tyv"
LANGUAGENAME_TO_LANGUAGEID[u"Udmurt"] = u"udm"
LANGUAGENAME_TO_LANGUAGEID[u"Ugaritic"] = u"uga"
LANGUAGENAME_TO_LANGUAGEID[u"Uighur; Uyghur"] = u"ug"
LANGUAGENAME_TO_LANGUAGEID[u"Ukrainian"] = u"uk"
LANGUAGENAME_TO_LANGUAGEID[u"Umbundu"] = u"umb"
LANGUAGENAME_TO_LANGUAGEID[u"Undetermined"] = u"und"
LANGUAGENAME_TO_LANGUAGEID[u"Urdu"] = u"ur"
LANGUAGENAME_TO_LANGUAGEID[u"Uzbek"] = u"uz"
LANGUAGENAME_TO_LANGUAGEID[u"Vai"] = u"vai"
LANGUAGENAME_TO_LANGUAGEID[u"Venda"] = u"ve"
LANGUAGENAME_TO_LANGUAGEID[u"Vietnamese"] = u"vi"
LANGUAGENAME_TO_LANGUAGEID[u"Volapük"] = u"vo"
LANGUAGENAME_TO_LANGUAGEID[u"Votic"] = u"vot"
LANGUAGENAME_TO_LANGUAGEID[u"Wakashan languages"] = u"wak"
LANGUAGENAME_TO_LANGUAGEID[u"Wolaitta; Wolaytta"] = u"wal"
LANGUAGENAME_TO_LANGUAGEID[u"Waray"] = u"war"
LANGUAGENAME_TO_LANGUAGEID[u"Washo"] = u"was"
LANGUAGENAME_TO_LANGUAGEID[u"Welsh"] = u"cy"
LANGUAGENAME_TO_LANGUAGEID[u"Sorbian languages"] = u"wen"
LANGUAGENAME_TO_LANGUAGEID[u"Walloon"] = u"wa"
LANGUAGENAME_TO_LANGUAGEID[u"Wolof"] = u"wo"
LANGUAGENAME_TO_LANGUAGEID[u"Kalmyk; Oirat"] = u"xal"
LANGUAGENAME_TO_LANGUAGEID[u"Xhosa"] = u"xh"
LANGUAGENAME_TO_LANGUAGEID[u"Yao"] = u"yao"
LANGUAGENAME_TO_LANGUAGEID[u"Yapese"] = u"yap"
LANGUAGENAME_TO_LANGUAGEID[u"Yiddish"] = u"yi"
LANGUAGENAME_TO_LANGUAGEID[u"Yoruba"] = u"yo"
LANGUAGENAME_TO_LANGUAGEID[u"Yupik languages"] = u"ypk"
LANGUAGENAME_TO_LANGUAGEID[u"Zapotec"] = u"zap"
LANGUAGENAME_TO_LANGUAGEID[u"Blissymbols; Blissymbolics; Bliss"] = u"zbl"
LANGUAGENAME_TO_LANGUAGEID[u"Zenaga"] = u"zen"
LANGUAGENAME_TO_LANGUAGEID[u"Standard Moroccan Tamazight"] = u"zgh"
LANGUAGENAME_TO_LANGUAGEID[u"Zhuang; Chuang"] = u"za"
LANGUAGENAME_TO_LANGUAGEID[u"Zande languages"] = u"znd"
LANGUAGENAME_TO_LANGUAGEID[u"Zulu"] = u"zu"
LANGUAGENAME_TO_LANGUAGEID[u"Zuni"] = u"zun"
LANGUAGENAME_TO_LANGUAGEID[u"Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"] = u"zza"